(()=>{
'use strict';
// Keep browser analytics on the same origin. The server endpoint owns the
// event allowlist/sanitization boundary and can evolve without exposing a
// direct third-party ingestion URL in every client.
const ENDPOINT='/api/event';
const productionHosts=new Set(['www.missionratedhq.com','missionratedhq.com','mission-rated-beta.vercel.app']);
if(!productionHosts.has(location.hostname))return;

function ensureGlobalFeedback(){
  if(document.getElementById('mrFeedbackButton'))return;
  const FEEDBACK_ENDPOINT='https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/submit-beta-feedback';
  const style=document.createElement('style');
  style.id='mrGlobalFeedbackStyle';
  style.textContent=`#mrFeedbackButton{position:fixed!important;right:14px!important;bottom:20px!important;z-index:2147483000!important;min-height:54px!important;padding:14px 17px!important;border:2px solid #8ef5ff!important;border-radius:999px!important;background:#00e5ff!important;color:#02101d!important;font:900 12px/1 Inter,sans-serif!important;cursor:pointer!important}#mrGlobalFeedbackModal{position:fixed;inset:0;z-index:2147483001;display:none;align-items:flex-end;justify-content:center;background:#000b;padding:16px}#mrGlobalFeedbackModal.open{display:flex}#mrGlobalFeedbackModal .mr-gf-sheet{width:min(540px,100%);background:#061725;color:#f5f8fa;border:1px solid #355d73;border-radius:18px;padding:18px}#mrGlobalFeedbackModal .mr-gf-choice,#mrGlobalFeedbackModal select,#mrGlobalFeedbackModal textarea,#mrGlobalFeedbackModal input,#mrGlobalFeedbackModal .mr-gf-send{min-height:44px;margin-top:10px}`;
  document.head.appendChild(style);
  const button=document.createElement('button');button.id='mrFeedbackButton';button.type='button';button.textContent='💬 Give Feedback';document.body.appendChild(button);
  const modal=document.createElement('div');modal.id='mrGlobalFeedbackModal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML=`<div class="mr-gf-sheet"><button class="mr-gf-close" type="button">×</button><h2>Help make Mission Rated better.</h2><div><button class="mr-gf-choice" data-v="yes">👍 Yes</button><button class="mr-gf-choice" data-v="partly">😐 Partly</button><button class="mr-gf-choice" data-v="no">👎 No</button></div><select class="mr-gf-category"><option value="general">General experience</option><option value="data_issue">Wrong / outdated data</option></select><textarea maxlength="1200"></textarea><input class="mr-gf-email" type="email"><button class="mr-gf-send">Send feedback</button></div>`;document.body.appendChild(modal);
  let helpful='';const close=()=>modal.classList.remove('open');button.addEventListener('click',()=>modal.classList.add('open'));modal.querySelector('.mr-gf-close').addEventListener('click',close);modal.querySelectorAll('.mr-gf-choice').forEach(c=>c.addEventListener('click',()=>helpful=c.dataset.v||''));modal.querySelector('.mr-gf-send').addEventListener('click',async()=>{const note=modal.querySelector('textarea').value.trim();if(!helpful&&!note)return;const payload={feedback_type:'general',helpful,message:note,item_name:document.title,contact_email:modal.querySelector('.mr-gf-email').value,page_path:location.pathname,website:''};try{await fetch(FEEDBACK_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});close()}catch{}});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureGlobalFeedback,{once:true});else ensureGlobalFeedback();
const clean=s=>String(s??'').trim();const qs=new URLSearchParams(location.search);try{const m=qs.get('mr_analytics');if(m==='off')localStorage.setItem('mr_analytics_optout','1');if(m==='on')localStorage.removeItem('mr_analytics_optout');if(localStorage.getItem('mr_analytics_optout')==='1')return}catch{}
const embedded=(()=>{try{return window.self!==window.top||qs.get('embedded')==='1'}catch{return true}})();const getId=(key,storage)=>{try{let v=storage.getItem(key);if(!v){v=crypto.randomUUID();storage.setItem(key,v)}return v}catch{return null}};const session=getId('mr_analytics_session',sessionStorage);const visitor=getId('mr_analytics_visitor',localStorage);const referralToken=getId('mr_share_referral_token',localStorage);const referrerHost=(()=>{try{return document.referrer?new URL(document.referrer).hostname.replace(/^www\./,''):null}catch{return null}})();const currentAcquisition={utm_source:qs.get('utm_source'),utm_medium:qs.get('utm_medium'),utm_campaign:qs.get('utm_campaign')||qs.get('campaign'),referral_code:qs.get('mr_ref')||qs.get('ref')};const acquisition=(()=>{try{const key='mr_acquisition_first_touch',existing=JSON.parse(localStorage.getItem(key)||'null');if(existing)return existing;const has=Object.values(currentAcquisition).some(Boolean);if(has)localStorage.setItem(key,JSON.stringify(currentAcquisition));return has?currentAcquisition:{}}catch{return currentAcquisition}})();
const targetContext=el=>{const card=el?.closest?.('[data-business-id],[data-school-id],[data-installation-id],[data-deal-id],[data-id],.card');if(card?.dataset?.dealId)return {target_type:'deal',target_id:card.dataset.dealId};if(card?.dataset?.businessId)return {target_type:'business',target_id:card.dataset.businessId};if(qs.get('deal'))return {target_type:'deal',target_id:qs.get('deal')};return {}};
const send=(eventName,extra={})=>{const payload={event_name:eventName,path:location.pathname||'/',session_id:session,visitor_id:visitor,referrer_host:referrerHost,...acquisition,...extra};try{fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload),keepalive:true,credentials:'same-origin'}).catch(()=>{})}catch{}};window.mrTrack=send;window.mrConfirmWeekendBriefSignup=(surface='unknown')=>send('weekend_brief_signup_confirmed',{signup_surface:clean(surface)||'unknown'});window.mrReferralUrl=(url=location.href)=>{try{const dest=new URL(url,location.href);if(dest.origin!==location.origin)return dest.toString();if(referralToken)dest.searchParams.set('mr_ref',referralToken);if(!dest.searchParams.get('utm_source'))dest.searchParams.set('utm_source','mission-rated-share');if(!dest.searchParams.get('utm_medium'))dest.searchParams.set('utm_medium','referral');return dest.toString()}catch{return url}};
if(!embedded){send('page_view');if(currentAcquisition.referral_code)send('referral_visit',{referral_code:currentAcquisition.referral_code})}
document.addEventListener('click',e=>{const el=e.target?.closest?.('a,button');if(!el)return;const text=clean(el.textContent).toLowerCase();const ctx=targetContext(el);if(el.classList?.contains('mrDealAction')||el.dataset?.dealAction==='get-deal')return send('deal_outbound_click',{...ctx,deal_source:clean(el.dataset?.dealSource)||'unknown'});if(el.id==='mrShareAction'||el.dataset?.dealAction==='share'||/^↗?\s*share\b/.test(text)){const shareTarget=clean(el.dataset?.shareTarget)||clean(el.getAttribute?.('href'))||location.href;let referralApplied=false;try{const u=new URL(window.mrReferralUrl(shareTarget),location.href);referralApplied=u.origin===location.origin&&u.searchParams.has('mr_ref')}catch{}return send('share_action',{...ctx,share_surface:clean(el.dataset?.shareSurface)||location.pathname||'unknown',referral_applied:referralApplied})}},true);
})();