(async()=>{'use strict';
const {SUPABASE_FUNCTIONS_ROOT}=await import('/lib/config.js');
const ROOT=SUPABASE_FUNCTIONS_ROOT;
const AUTO=ROOT+'public-auto-dealers',VOTES=ROOT+'public-quick-rank-votes',SUBMIT=ROOT+'quick-rank-vote';
let dealers=[],people=[],voteMap=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=(t,id)=>`${t}:${id}`;
const voter=()=>{let k=localStorage.getItem('mr_quick_voter');if(!k){k=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem('mr_quick_voter',k)}return k};
const selection=(t,id)=>Number(localStorage.getItem(`mr_vote_${key(t,id)}`)||0);
function css(){if(document.getElementById('mrAutoVoteStyle'))return;const s=document.createElement('style');s.id='mrAutoVoteStyle';s.textContent='.mrAutoVote{display:flex;align-items:center;gap:7px;margin:10px 0 2px;padding:8px;border:1px solid #31566b;border-radius:10px;background:#03131f}.mrAutoVoteLabel{font-size:9px;color:#b8c8cf;line-height:1.25;margin-right:auto}.mrAutoVoteBtn{border:1px solid #31566b;background:#0a2636;min-width:58px;height:38px;border-radius:9px;font-size:13px;font-weight:950;cursor:pointer}.mrAutoVoteBtn.up{color:#72f0b5}.mrAutoVoteBtn.down{color:#ff9292}.mrAutoVoteBtn[aria-pressed="true"]{border-color:#00e5ff;box-shadow:0 0 0 1px #00e5ff inset}.mrAutoVoteBtn:disabled{opacity:.45}.mrAutoVoteNote{font-size:8px;color:#78929e;margin-top:4px;line-height:1.35}@media(max-width:640px){.mrAutoVote{width:100%}.mrAutoVoteBtn{min-width:64px;height:44px;font-size:14px}.mrAutoVoteLabel{font-size:10px}}';document.head.appendChild(s)}
function byName(type){const arr=type==='dealer'?dealers:people;return new Map(arr.map(x=>[String(x.name||'').trim(),x]));}
function attach(card,type,item){if(!card||!item?.id)return;const name=String(item.name||'this item'),v=voteMap.get(key(type,item.id))||{up:0,down:0},mine=selection(type,item.id);let box=card.querySelector('.mrAutoVote');if(!box){box=document.createElement('div');box.className='mrAutoVote';const anchor=card.querySelector('.mrAutoBadges,.badges')||card.querySelector('h2,h3');anchor?.insertAdjacentElement('afterend',box);if(!anchor)card.prepend(box)}if(!box)return;box.innerHTML=`<span class="mrAutoVoteLabel">Used this ${type==='dealer'?'dealer':'salesperson'}?<br>Rate your experience</span><button class="mrAutoVoteBtn up" aria-label="Recommend ${esc(name)}" aria-pressed="${mine===1}">▲ ${v.up||0}</button><button class="mrAutoVoteBtn down" aria-label="Do not recommend ${esc(name)}" aria-pressed="${mine===-1}">▼ ${v.down||0}</button>`;box.querySelector('.up')?.addEventListener('click',e=>submit(type,item.id,1,e.currentTarget));box.querySelector('.down')?.addEventListener('click',e=>submit(type,item.id,-1,e.currentTarget));let n=card.querySelector('.mrAutoVoteNote');if(!n){n=document.createElement('div');n.className='mrAutoVoteNote';box.insertAdjacentElement('afterend',n)}n.textContent='Community signal only • does not create an MR score or User Verified badge.'}
function mount(rootId,type){const root=document.getElementById(rootId);if(!root)return;const map=byName(type);for(const card of root.querySelectorAll('.card')){const name=card.querySelector('h2,h3')?.textContent?.trim(),item=map.get(name);if(item)attach(card,type,item)}}
function detail(){if(!/\/auto(?:\.html)?$/.test(location.pathname))return false;const p=new URLSearchParams(location.search),type=p.get('type')==='salesperson'?'salesperson':'dealer',id=p.get('id'),item=(type==='dealer'?dealers:people).find(x=>String(x.id)===String(id));if(item)attach(document.getElementById('content'),type,item);return true}
function render(){if(detail())return;mount('dealerData','dealer');mount('salespeopleData','salesperson')}
async function submit(type,id,dir,btn){const box=btn.closest('.mrAutoVote');box?.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await fetch(SUBMIT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_type:type,item_id:id,vote:dir,voter_key:voter()})});if(!r.ok)throw Error(r.status);const v=await r.json();voteMap.set(key(type,id),v);localStorage.setItem(`mr_vote_${key(type,id)}`,String(dir));render()}catch{box?.setAttribute('title','Could not save feedback. Try again.')}finally{box?.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function run(){css();try{const [a,v]=await Promise.all([fetch(AUTO),fetch(VOTES)]);if(a.ok){const j=await a.json();dealers=j.dealers||[];people=j.salespeople||[]}if(v.ok){const j=await v.json();voteMap=new Map((j.votes||[]).map(x=>[key(x.item_type,x.item_id),x]))}}catch{}let n=0;const t=setInterval(()=>{render();if(++n>24)clearInterval(t)},350);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();