(()=>{'use strict';
const API='https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/public-explore';
const norm=s=>String(s||'').trim().toLowerCase();
const fmt=v=>{if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})};
const days=v=>{if(!v)return null;const d=new Date(v);if(Number.isNaN(d.getTime()))return null;return Math.ceil((d.getTime()-Date.now())/86400000)};
function css(){if(document.getElementById('mrDealExpiryStyle'))return;const s=document.createElement('style');s.id='mrDealExpiryStyle';s.textContent='.mrDealExpiry{display:inline-flex;align-items:center;gap:5px;margin-top:6px;padding:4px 6px;border:1px solid #4b6170;border-radius:999px;font-size:8px;font-weight:850;color:#b9cbd3;background:#071923}.mrDealExpiry.soon{border-color:#8a722e;color:#ffd36d;background:#211d0d}.mrDealExpiry.expired{border-color:#7b3f3f;color:#ffaaaa;background:#261414}@media(max-width:640px){.mrDealExpiry{font-size:9px;padding:5px 7px}}';document.head.appendChild(s)}
function pill(end){if(!end)return'';const n=days(end),cls=n!=null&&n<0?' expired':n!=null&&n<=30?' soon':'';return `<span class="mrDealExpiry${cls}">${n!=null&&n<0?'Expired':'Offer ends'} ${fmt(end)}</span>`}
function bestDeals(deals){const byBusiness=new Map();for(const d of deals){const k=norm(d.businesses?.name);if(!k)continue;const prev=byBusiness.get(k);if(!prev||Number(d.military_value_weight||0)>Number(prev.military_value_weight||0)||(Number(d.military_value_weight||0)===Number(prev.military_value_weight||0)&&Date.parse(d.verified_at||0)>Date.parse(prev.verified_at||0)))byBusiness.set(k,d)}return byBusiness}
function decorateBusinessCards(deals){const grid=document.getElementById('businessGrid');if(!grid)return;const byBusiness=bestDeals(deals);for(const card of grid.querySelectorAll('.card')){card.querySelectorAll('.mrDealExpiry').forEach(x=>x.remove());const d=byBusiness.get(norm(card.querySelector('h2,h3')?.textContent));if(!d?.ends_at)continue;const offer=card.querySelector('.offer')||card.querySelector('.badges')||card.querySelector('h2,h3');offer?.insertAdjacentHTML('afterend',pill(d.ends_at))}}
function decorateHomepage(deals){const grid=document.getElementById('dealGrid');if(!grid)return;const pools=new Map();for(const d of deals){const k=norm(d.businesses?.name||d.title);const a=pools.get(k)||[];a.push(d);pools.set(k,a)}for(const card of grid.querySelectorAll('.card')){card.querySelectorAll('.mrDealExpiry').forEach(x=>x.remove());const k=norm(card.querySelector('h2,h3')?.textContent),a=pools.get(k)||[];if(!a.length)continue;const d=a.shift();const html=pill(d.ends_at);if(!html)continue;const offer=card.querySelector('.offer')||card.querySelector('.badges')||card.querySelector('h2,h3');offer?.insertAdjacentHTML('afterend',html)}}
function decorateMilitary(deals){if(!/\/military-value(?:\.html)?$/.test(location.pathname))return;const grid=document.getElementById('grid');if(!grid)return;const byBusiness=bestDeals(deals);for(const card of grid.querySelectorAll('.card')){card.querySelectorAll('.mrDealExpiry').forEach(x=>x.remove());const d=byBusiness.get(norm(card.querySelector('h2,h3')?.textContent));if(!d?.ends_at)continue;const offer=card.querySelector('.offer')||card.querySelector('.badges');offer?.insertAdjacentHTML('afterend',pill(d.ends_at))}}
function apply(deals){decorateBusinessCards(deals);decorateHomepage(deals);decorateMilitary(deals)}
async function run(){css();try{const r=await fetch(API,{headers:{accept:'application/json'}});if(!r.ok)return;const j=await r.json();const deals=j.deals||[];apply(deals);for(const id of ['businessGrid','dealGrid','grid']){const el=document.getElementById(id);if(el)new MutationObserver(()=>{clearTimeout(el._mrExpiryT);el._mrExpiryT=setTimeout(()=>apply(deals),80)}).observe(el,{childList:true,subtree:false})}setTimeout(()=>apply(deals),600);setTimeout(()=>apply(deals),1500)}catch{}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();