(()=>{
'use strict';
if(location.pathname!=='/'&&location.pathname!=='/index.html')return;
const API='https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/public-explore';
const norm=s=>String(s||'').trim().toLowerCase();
let businesses=new Map(),deals=[];
function css(){if(document.getElementById('mrDiscoverySortStyle'))return;const s=document.createElement('style');s.id='mrDiscoverySortStyle';s.textContent=`
.mrSortRow{display:flex;gap:7px;align-items:center;justify-content:flex-end;margin:0 0 10px}.mrSortRow label{font-size:8px;font-weight:900;color:#91a8b2;letter-spacing:.08em}.mrSortRow select{width:auto;min-width:190px;padding:8px 10px;font-size:9px}.mrEvidenceLine{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.mrEvidenceChip{font-size:7px;border:1px solid #31566b;border-radius:999px;padding:4px 6px;color:#a9c0ca}.mrEvidenceChip.strong{border-color:#2d7668;color:#9df0d7}.mrEvidenceChip.warn{border-color:#76502c;color:#ffd59c}.mrMobileActions{display:none}
@media(max-width:640px){.mrSortRow{justify-content:stretch;align-items:stretch;flex-direction:column}.mrSortRow select{width:100%;min-width:0}.card .links{gap:6px}.card .links .btn,.card .links .source{min-height:40px;display:inline-flex;align-items:center}.mrMobileActions{display:block;font-size:8px;color:#78939f;margin-top:4px}}
`;document.head.appendChild(s)}
function cardName(card){return norm(card.querySelector('h3')?.textContent)}
function addControls(){const places=document.getElementById('places'),dealsSec=document.getElementById('deals');if(places&&!document.getElementById('mrPlaceSort')){const r=document.createElement('div');r.className='mrSortRow';r.innerHTML='<label for="mrPlaceSort">SORT PLACES</label><select id="mrPlaceSort"><option value="military">Strongest military value</option><option value="rating">Highest sourced public rating</option><option value="reviews">Most public reviews</option><option value="official">Official-source evidence first</option><option value="name">Name A–Z</option></select>';const anchor=places.querySelector('#mrTrustControls')||places.querySelector('.context');anchor?.after(r);r.querySelector('select').addEventListener('change',sortPlaces)}if(dealsSec&&!document.getElementById('mrDealSort')){const r=document.createElement('div');r.className='mrSortRow';r.innerHTML='<label for="mrDealSort">SORT OFFERS</label><select id="mrDealSort"><option value="value">Strongest verified value</option><option value="fresh">Most recently verified</option><option value="official">Official-source first</option><option value="name">Business A–Z</option></select>';dealsSec.querySelector('.context')?.after(r);r.querySelector('select').addEventListener('change',sortDeals)}}
function ratingNum(d){return Number(d?.public_rating?.rating)||-1}function reviewNum(d){return Number(d?.public_rating?.sample_size)||0}function stamp(d){return Date.parse(d?.best_military_offer?.verified_at||d?.source_checked_at||d?.public_rating?.observed_at||0)||0}
function sortPlaces(){const grid=document.getElementById('businessGrid'),sel=document.getElementById('mrPlaceSort');if(!grid||!sel||!businesses.size)return;const cards=[...grid.children].filter(x=>x.classList.contains('card'));cards.sort((a,b)=>{const A=businesses.get(cardName(a)),B=businesses.get(cardName(b));switch(sel.value){case'rating':return ratingNum(B)-ratingNum(A)||reviewNum(B)-reviewNum(A);case'reviews':return reviewNum(B)-reviewNum(A)||ratingNum(B)-ratingNum(A);case'official':return Number(!!B?.official_verified)-Number(!!A?.official_verified)||Number(B?.military_value_weight||0)-Number(A?.military_value_weight||0);case'name':return String(A?.name||'').localeCompare(String(B?.name||''));default:return Number(B?.military_value_weight||0)-Number(A?.military_value_weight||0)||Number(!!B?.official_verified)-Number(!!A?.official_verified)}});cards.forEach(c=>grid.appendChild(c));decorate(cards,'business')}
function sortDeals(){const grid=document.getElementById('dealGrid'),sel=document.getElementById('mrDealSort');if(!grid||!sel||!deals.length)return;const used=new Set(),cards=[...grid.children].filter(x=>x.classList.contains('card')).map((card,i)=>{const n=cardName(card);const idx=deals.findIndex((d,j)=>!used.has(j)&&norm(d.businesses?.name||d.title)===n);if(idx>=0)used.add(idx);return{card,d:idx>=0?deals[idx]:null,i}});cards.sort((a,b)=>{const A=a.d,B=b.d;switch(sel.value){case'fresh':return stamp(B)-stamp(A);case'official':return Number(!!B?.official_verified)-Number(!!A?.official_verified)||Number(B?.military_value_weight||0)-Number(A?.military_value_weight||0);case'name':return String(B?.businesses?.name||'').localeCompare(String(A?.businesses?.name||''))*-1;default:return Number(B?.military_value_weight||0)-Number(A?.military_value_weight||0)||Number(!!B?.official_verified)-Number(!!A?.official_verified)}});cards.forEach(x=>grid.appendChild(x.card));decorate(cards.map(x=>x.card),'deal')}
function decorate(cards,type){for(const card of cards){if(card.querySelector('.mrEvidenceLine'))continue;let d;if(type==='business')d=businesses.get(cardName(card));else d=deals.find(x=>norm(x.businesses?.name||x.title)===cardName(card));if(!d)continue;const row=document.createElement('div');row.className='mrEvidenceLine';const bits=[];bits.push(`<span class="mrEvidenceChip ${d.official_verified?'strong':'warn'}">${d.official_verified?'Official provenance':'Source-backed'}</span>`);if(d.public_rating?.rating!=null)bits.push(`<span class="mrEvidenceChip strong">Public rating sourced</span>`);if(d.community_verified)bits.push('<span class="mrEvidenceChip strong">User Verified</span>');if(d.mission_score_status!=='rated')bits.push('<span class="mrEvidenceChip">MR Building</span>');row.innerHTML=bits.join('');const links=card.querySelector('.links');if(links)card.insertBefore(row,links);else card.appendChild(row)}}
function apply(){sortPlaces();sortDeals()}
async function run(){css();addControls();try{const r=await fetch(API,{headers:{accept:'application/json'}});if(!r.ok)throw Error(r.status);const j=await r.json();businesses=new Map((j.businesses||[]).map(x=>[norm(x.name),x]));deals=j.deals||[];apply();for(const id of ['businessGrid','dealGrid']){const el=document.getElementById(id);if(el)new MutationObserver(()=>{clearTimeout(el._mrSortT);el._mrSortT=setTimeout(apply,60)}).observe(el,{childList:true,subtree:false})}setTimeout(apply,500);setTimeout(apply,1400)}catch{}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();