(async()=>{
'use strict';
if(location.pathname!=='/'&&location.pathname!=='/index.html')return;
const {SUPABASE_FUNCTIONS_ROOT}=await import('/lib/config.js');
const ROOT=SUPABASE_FUNCTIONS_ROOT;
const API=ROOT+'public-explore',VOTES=ROOT+'public-quick-rank-votes',MEDICAL=ROOT+'public-medical';
const norm=s=>String(s||'').trim().toLowerCase(),vkey=(t,id)=>`${t}:${id}`,day=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?new Date(t).toISOString().slice(0,10):''};
const validRating=d=>d?.public_rating?.rating!=null&&/^https:\/\//i.test(String(d?.public_rating?.source_url||''))&&Number(d?.public_rating?.sample_size)>0;
let businesses=new Map(),deals=[],voteMap=new Map(),tricareIds=new Set();
function css(){if(document.getElementById('mrDiscoverySortStyle'))return;const s=document.createElement('style');s.id='mrDiscoverySortStyle';s.textContent=`
.mrSortRow{display:flex;gap:7px;align-items:center;justify-content:flex-end;margin:0 0 10px;flex-wrap:wrap}.mrSortRow label{font-size:8px;font-weight:900;color:#91a8b2;letter-spacing:.08em}.mrSortRow select{width:auto;min-width:190px;padding:8px 10px;font-size:9px}.mrEvidenceLine{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.mrEvidenceChip{font-size:7px;border:1px solid #31566b;border-radius:999px;padding:4px 6px;color:#a9c0ca}.mrEvidenceChip.strong{border-color:#2d7668;color:#9df0d7}.mrEvidenceChip.warn{border-color:#76502c;color:#ffd59c}.mrEvidenceChip.value{border-color:#7b672f;color:#ffd36d;background:#1a1b17}.mrMobileActions{display:none}
@media(max-width:640px){.mrSortRow{justify-content:stretch;align-items:stretch;flex-direction:column}.mrSortRow select{width:100%;min-width:0}.card .links{gap:6px}.card .links .btn,.card .links .source{min-height:40px;display:inline-flex;align-items:center}.mrMobileActions{display:block;font-size:8px;color:#78939f;margin-top:4px}}
`;document.head.appendChild(s)}
function cardName(card){return norm(card.querySelector('h3')?.textContent)}
function addControls(){const places=document.getElementById('places'),dealsSec=document.getElementById('deals');if(places&&!document.getElementById('mrPlaceSort')){const r=document.createElement('div');r.className='mrSortRow';r.innerHTML='<label for="mrEvidenceFilter">FILTER EVIDENCE</label><select id="mrEvidenceFilter"><option value="all">All evidence states</option><option value="military">Verified military value</option><option value="tricare">TRICARE accepted • sourced</option><option value="official">Official-source verified</option><option value="rating">Sourced public rating</option><option value="user">User Verified</option><option value="rated">Mission Rated score available</option></select><label for="mrPlaceSort">SORT PLACES</label><select id="mrPlaceSort"><option value="military">Strongest military value</option><option value="rating">Highest sourced public rating</option><option value="reviews">Most public reviews</option><option value="official">Official-source evidence first</option><option value="fresh">Freshest evidence first</option><option value="community">Community ▲ net signal</option><option value="name">Name A–Z</option></select>';const anchor=places.querySelector('#mrTrustControls')||places.querySelector('.context');anchor?.after(r);r.querySelector('#mrPlaceSort').addEventListener('change',sortPlaces);r.querySelector('#mrEvidenceFilter').addEventListener('change',filterPlaces)}if(dealsSec&&!document.getElementById('mrDealSort')){const r=document.createElement('div');r.className='mrSortRow';r.innerHTML='<label for="mrDealSort">SORT OFFERS</label><select id="mrDealSort"><option value="value">Strongest verified value</option><option value="fresh">Most recently verified</option><option value="official">Official-source first</option><option value="name">Business A–Z</option></select>';dealsSec.querySelector('.context')?.after(r);r.querySelector('select').addEventListener('change',sortDeals)}}
function ratingNum(d){return validRating(d)?Number(d.public_rating.rating)||-1:-1}function reviewNum(d){return validRating(d)?Number(d.public_rating.sample_size)||0:0}function stamp(d){return Date.parse(d?.best_military_offer?.verified_at||d?.verified_at||d?.source_checked_at||(validRating(d)?d?.public_rating?.observed_at:null)||0)||0}function militaryNum(d){return Number(d?.military_value_weight)||0}
function militaryCompare(A,B){return militaryNum(B)-militaryNum(A)||Number(!!B?.official_verified)-Number(!!A?.official_verified)||stamp(B)-stamp(A)||reviewNum(B)-reviewNum(A)||String(A?.name||'').localeCompare(String(B?.name||''))}
function community(d){const v=voteMap.get(vkey('business',d?.id));return {net:Number(v?.net)||0,total:Number(v?.total)||0,up:Number(v?.up)||0,down:Number(v?.down)||0}}
function evidenceMatch(d,mode){if(mode==='military')return militaryNum(d)>0||d?.has_active_military_offer===true;if(mode==='tricare')return tricareIds.has(String(d?.id));if(mode==='official')return d?.official_verified===true;if(mode==='rating')return validRating(d);if(mode==='user')return d?.community_verified===true;if(mode==='rated')return d?.mission_score_status==='rated'&&d?.mission_score!=null;return true}
function filterPlaces(){const grid=document.getElementById('businessGrid'),sel=document.getElementById('mrEvidenceFilter');if(!grid||!sel||!businesses.size)return;let shown=0;for(const card of [...grid.children].filter(x=>x.classList.contains('card'))){const d=businesses.get(cardName(card)),show=!!d&&evidenceMatch(d,sel.value);card.hidden=!show;if(show)shown++}const count=document.getElementById('resultCount');if(count)count.textContent=`${shown} shown`}
function sortPlaces(){const grid=document.getElementById('businessGrid'),sel=document.getElementById('mrPlaceSort');if(!grid||!sel||!businesses.size)return;const cards=[...grid.children].filter(x=>x.classList.contains('card'));cards.sort((a,b)=>{const A=businesses.get(cardName(a)),B=businesses.get(cardName(b));switch(sel.value){case'rating':return ratingNum(B)-ratingNum(A)||reviewNum(B)-reviewNum(A)||militaryCompare(A,B);case'reviews':return reviewNum(B)-reviewNum(A)||ratingNum(B)-ratingNum(A)||militaryCompare(A,B);case'official':return Number(!!B?.official_verified)-Number(!!A?.official_verified)||militaryCompare(A,B);case'fresh':return stamp(B)-stamp(A)||militaryCompare(A,B);case'community':{const av=community(A),bv=community(B);return bv.net-av.net||bv.total-av.total||militaryCompare(A,B)}case'name':return String(A?.name||'').localeCompare(String(B?.name||''));default:return militaryCompare(A,B)}});cards.forEach(c=>grid.appendChild(c));decorate(cards,'business');filterPlaces()}
function sortDeals(){const grid=document.getElementById('dealGrid'),sel=document.getElementById('mrDealSort');if(!grid||!sel||!deals.length)return;const used=new Set(),cards=[...grid.children].filter(x=>x.classList.contains('card')).map((card,i)=>{const n=cardName(card);const idx=deals.findIndex((d,j)=>!used.has(j)&&norm(d.businesses?.name||d.title)===n);if(idx>=0)used.add(idx);return{card,d:idx>=0?deals[idx]:null,i}});cards.sort((a,b)=>{const A=a.d,B=b.d;switch(sel.value){case'fresh':return stamp(B)-stamp(A)||militaryCompare(A,B);case'official':return Number(!!B?.official_verified)-Number(!!A?.official_verified)||militaryCompare(A,B);case'name':return String(A?.businesses?.name||A?.title||'').localeCompare(String(B?.businesses?.name||B?.title||''));default:return militaryCompare(A,B)}});cards.forEach(x=>grid.appendChild(x.card));decorate(cards.map(x=>x.card),'deal')}
function decorate(cards,type){for(const card of cards){let row=card.querySelector('.mrEvidenceLine');let d;if(type==='business')d=businesses.get(cardName(card));else d=deals.find(x=>norm(x.businesses?.name||x.title)===cardName(card));if(!d)continue;if(!row){row=document.createElement('div');row.className='mrEvidenceLine';const links=card.querySelector('.links');if(links)card.insertBefore(row,links);else card.appendChild(row)}const bits=[];bits.push(`<span class="mrEvidenceChip ${d.official_verified?'strong':'warn'}">${d.official_verified?'Official provenance':'Source-backed'}</span>`);if(militaryNum(d)>0)bits.push(`<span class="mrEvidenceChip value">Military value ${militaryNum(d)}</span>`);if(type==='business'&&tricareIds.has(String(d.id)))bits.push('<span class="mrEvidenceChip strong">TRICARE acceptance sourced</span>');const verified=day(d?.best_military_offer?.verified_at||d?.verified_at);if(verified)bits.push(`<span class="mrEvidenceChip strong">Verified ${verified}</span>`);const ends=day(d?.ends_at);if(ends)bits.push(`<span class="mrEvidenceChip">Ends ${ends}</span>`);if(validRating(d))bits.push(`<span class="mrEvidenceChip strong">Public rating sourced • ${reviewNum(d)} reviews</span>`);if(d.community_verified)bits.push('<span class="mrEvidenceChip strong">User Verified</span>');if(d.mission_score_status!=='rated')bits.push('<span class="mrEvidenceChip">MR Building</span>');if(type==='business'){const v=community(d);if(v.total)bits.push(`<span class="mrEvidenceChip">Community ▲${v.up} ▼${v.down}</span>`)}row.innerHTML=bits.join('')}}
function apply(){sortPlaces();sortDeals();filterPlaces()}
async function run(){css();addControls();try{const [r,v,m]=await Promise.all([fetch(API,{headers:{accept:'application/json'}}),fetch(VOTES,{headers:{accept:'application/json'}}),fetch(MEDICAL,{headers:{accept:'application/json'}})]);if(!r.ok)throw Error(r.status);const j=await r.json();businesses=new Map((j.businesses||[]).map(x=>[norm(x.name),x]));deals=j.deals||[];if(v.ok){const q=await v.json();voteMap=new Map((q.votes||[]).map(x=>[vkey(x.item_type,x.item_id),x]))}if(m.ok){const q=await m.json();tricareIds=new Set((q.providers||[]).filter(x=>x.tricare_accepted).map(x=>String(x.id)))}apply();for(const id of ['businessGrid','dealGrid']){const el=document.getElementById(id);if(el)new MutationObserver(()=>{clearTimeout(el._mrSortT);el._mrSortT=setTimeout(apply,60)}).observe(el,{childList:true,subtree:false})}setTimeout(apply,500);setTimeout(apply,1400)}catch{}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();