(async()=>{
  if (document.getElementById('mrFeedbackButton')) return;

  const {SUPABASE_FUNCTIONS_ROOT}=await import('/lib/config.js');
  const FEEDBACK_URL=SUPABASE_FUNCTIONS_ROOT+'submit-beta-feedback';
  const css=`
  .mr-feedback-btn{position:fixed;right:0;top:58%;transform:translateY(-50%);z-index:10020;min-height:56px;border:2px solid #8ef5ff;border-right:0;background:#00e5ff;color:#02101d;border-radius:16px 0 0 16px;padding:15px 14px 15px 16px;font:900 12px/1 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:.01em;box-shadow:0 14px 38px #0009,0 0 0 4px #00e5ff24,0 0 26px #00e5ff55;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:6px;transition:transform .15s ease,box-shadow .15s ease}.mr-feedback-btn:hover,.mr-feedback-btn:focus-visible{transform:translateY(-50%) translateX(-3px) scale(1.03);box-shadow:0 18px 44px #000a,0 0 0 5px #00e5ff30,0 0 34px #00e5ff77}.mr-feedback-btn:focus-visible{outline:3px solid #fff;outline-offset:3px}
  .mr-feedback-modal{position:fixed;inset:0;z-index:11000;display:none;align-items:flex-end;justify-content:center;padding:16px;background:#000b}.mr-feedback-modal.open{display:flex}
  .mr-feedback-sheet{width:min(560px,100%);max-height:min(88vh,760px);overflow:auto;border:1px solid #355d73;border-radius:18px;background:#061725;color:#f5f8fa;padding:20px;box-shadow:0 25px 80px #000d;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
  .mr-feedback-top{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.mr-feedback-top h2{margin:4px 0 6px;font-size:22px}.mr-feedback-top p{margin:0;color:#a8bbc5;font-size:11px;line-height:1.5}.mr-feedback-close{border:0;background:transparent;color:#c8d6dc;font-size:26px;cursor:pointer;min-width:44px;min-height:44px}
  .mr-feedback-label{display:block;margin:13px 0 6px;color:#bdd0d8;font-size:10px;font-weight:850}.mr-feedback-choices{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mr-feedback-choice{min-height:44px;padding:11px;border:1px solid #345c72;border-radius:9px;background:#082238;color:#e6f1f5;font-weight:850;cursor:pointer}.mr-feedback-choice.active{border-color:#00e5ff;background:#0a3b4e;color:#8ef5ff}
  .mr-feedback-sheet select,.mr-feedback-sheet textarea,.mr-feedback-sheet input{width:100%;padding:12px;border:1px solid #426176;border-radius:9px;background:#061b2d;color:#fff;font:inherit}.mr-feedback-sheet textarea{min-height:110px;resize:vertical}.mr-feedback-submit{margin-top:14px;width:100%;min-height:44px;border:1px solid #00e5ff;background:#00e5ff;color:#02101d;border-radius:9px;padding:11px;font-weight:900;cursor:pointer}.mr-feedback-submit:disabled{opacity:.6}.mr-feedback-note{margin-top:8px;color:#78909b;font-size:9px;line-height:1.45}.mr-feedback-success{text-align:center;padding:22px 4px}.mr-feedback-success strong{display:block;font-size:18px;margin-bottom:6px}.mr-feedback-hp{position:absolute!important;left:-10000px!important;opacity:0!important}
  @media(max-width:700px){.mr-feedback-btn{right:0;top:61%;bottom:auto;transform:translateY(-50%);min-height:58px;padding:15px 12px 15px 14px;font-size:0;border-radius:16px 0 0 16px}.mr-feedback-btn::after{content:'💬';font-size:22px;line-height:1}.mr-feedback-btn:hover,.mr-feedback-btn:focus-visible{transform:translateY(-50%) translateX(-2px) scale(1.03)}.mr-feedback-modal{padding:0}.mr-feedback-sheet{max-height:92dvh;border-radius:18px 18px 0 0;padding:18px 18px calc(18px + env(safe-area-inset-bottom))}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);

  const button=document.createElement('button');
  button.id='mrFeedbackButton';button.className='mr-feedback-btn';button.type='button';button.textContent='💬 Give Feedback';button.setAttribute('aria-label','Give feedback');button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-controls','mrFeedbackModal');
  document.body.appendChild(button);

  const modal=document.createElement('div');modal.className='mr-feedback-modal';modal.id='mrFeedbackModal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','mrFeedbackTitle');
  modal.innerHTML=`<div class="mr-feedback-sheet"><div id="mrFeedbackFormState"><div class="mr-feedback-top"><div><span style="font-size:8px;font-weight:900;color:#00e5ff">PUBLIC BETA • NO LOGIN</span><h2 id="mrFeedbackTitle">Help make Mission Rated better.</h2><p>Ten seconds is enough. Tap a rating and send it — details are optional.</p></div><button class="mr-feedback-close" type="button" aria-label="Close feedback">×</button></div><form id="mrFeedbackForm"><input class="mr-feedback-hp" tabindex="-1" autocomplete="off" name="website" id="mrFeedbackWebsite" aria-hidden="true"><label class="mr-feedback-label">Did this page help?</label><div class="mr-feedback-choices"><button type="button" class="mr-feedback-choice" data-helpful="yes">👍 Yes</button><button type="button" class="mr-feedback-choice" data-helpful="partly">😐 Partly</button><button type="button" class="mr-feedback-choice" data-helpful="no">👎 No</button></div><input type="hidden" id="mrFeedbackHelpful" value=""><label class="mr-feedback-label" for="mrFeedbackCategory">What is this about?</label><select id="mrFeedbackCategory"><option value="general">General experience</option><option value="data_issue">Wrong / outdated data</option><option value="schools">Schools</option><option value="military_discount">Military discount</option><option value="business">Business listing</option><option value="base_intel">Base / PCS information</option><option value="missing_info">Something is missing</option><option value="bug">Something is broken</option><option value="other">Other</option></select><label class="mr-feedback-label" for="mrFeedbackMessage">Anything else? <span style="font-weight:400;color:#78909b">(optional)</span></label><textarea id="mrFeedbackMessage" maxlength="1200" placeholder="Example: This discount expired, or I couldn't find childcare near Oceana."></textarea><label class="mr-feedback-label" for="mrFeedbackEmail">Email <span style="font-weight:400;color:#78909b">(optional)</span></label><input id="mrFeedbackEmail" type="email" maxlength="180" autocomplete="email" placeholder="Only if you'd like a reply"><div class="mr-feedback-note">Anonymous is fine. Do not submit sensitive personal, medical, financial, or operational information.</div><button class="mr-feedback-submit" id="mrFeedbackSubmit" type="submit">Send feedback</button></form></div><div class="mr-feedback-success" id="mrFeedbackSuccess" hidden><strong>✓ Got it. Thank you.</strong><span style="font-size:11px;color:#a8bbc5">Your feedback is in the Mission Rated review queue.</span></div></div>`;
  document.body.appendChild(modal);

  const form=modal.querySelector('#mrFeedbackForm'),formState=modal.querySelector('#mrFeedbackFormState'),success=modal.querySelector('#mrFeedbackSuccess');
  const helpful=modal.querySelector('#mrFeedbackHelpful');
  const open=()=>{form.reset();helpful.value='';modal.querySelectorAll('.mr-feedback-choice').forEach(x=>x.classList.remove('active'));formState.hidden=false;success.hidden=true;modal.classList.add('open');document.body.style.overflow='hidden';button.setAttribute('aria-expanded','true');setTimeout(()=>modal.querySelector('.mr-feedback-choice').focus(),30)};
  const close=()=>{modal.classList.remove('open');document.body.style.overflow='';button.setAttribute('aria-expanded','false');button.focus({preventScroll:true})};
  button.setAttribute('aria-expanded','false');button.addEventListener('click',open);modal.querySelector('.mr-feedback-close').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))close()});
  modal.querySelectorAll('.mr-feedback-choice').forEach(el=>el.addEventListener('click',()=>{modal.querySelectorAll('.mr-feedback-choice').forEach(x=>x.classList.remove('active'));el.classList.add('active');helpful.value=el.dataset.helpful||''}));
  form.addEventListener('submit',async e=>{e.preventDefault();const message=modal.querySelector('#mrFeedbackMessage').value.trim();if(!helpful.value&&!message){alert('Tap Yes, Partly, or No — or add a short note.');modal.querySelector('.mr-feedback-choice').focus();return}const submit=modal.querySelector('#mrFeedbackSubmit');const original=submit.textContent;submit.disabled=true;submit.textContent='Sending…';const payload={feedback_type:modal.querySelector('#mrFeedbackCategory').value==='data_issue'?'data_issue':'general',helpful:helpful.value,category:modal.querySelector('#mrFeedbackCategory').value,message,item_name:document.title,contact_email:modal.querySelector('#mrFeedbackEmail').value,page_path:location.pathname,website:modal.querySelector('#mrFeedbackWebsite').value};try{const r=await fetch(FEEDBACK_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(String(r.status));formState.hidden=true;success.hidden=false;setTimeout(close,1800)}catch{alert('We could not send that feedback. Please try again.')}finally{submit.disabled=false;submit.textContent=original)}});
})();

(async()=>{
  'use strict';
  const surfaceByPath={'/gas.html':'gas','/business.html':'business','/military-value.html':'military_deals','/savings.html':'military_deals','/medical.html':'medical'};
  const path=location.pathname||'/',surface=surfaceByPath[path];
  if(!surface||document.getElementById('mrHelpful'))return;
  const key=`mr_helpful:${surface}:${path}`;
  try{if(localStorage.getItem(key))return}catch{}
  const {SUPABASE_FUNCTIONS_ROOT}=await import('/lib/config.js');
  const ENDPOINT=SUPABASE_FUNCTIONS_ROOT+'product-event';
  const session=(()=>{try{let v=sessionStorage.getItem('mr_analytics_session');if(!v){v=crypto.randomUUID();sessionStorage.setItem('mr_analytics_session',v)}return v}catch{return null}})();
  const qs=new URLSearchParams(location.search);
  const referrerHost=(()=>{try{return document.referrer?new URL(document.referrer).hostname.replace(/^www\./,''):null}catch{return null}})();
  const style=document.createElement('style');style.textContent=`#mrHelpful{position:fixed;left:50%;bottom:18px;transform:translateX(-50%) translateY(18px);z-index:10010;width:min(430px,calc(100vw - 28px));padding:14px 15px;border:1px solid #315a73;border-radius:14px;background:#041521f2;color:#f5f8fa;box-shadow:0 18px 50px #0008;backdrop-filter:blur(14px);opacity:0;transition:.2s ease;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#mrHelpful.mrShow{opacity:1;transform:translateX(-50%) translateY(0)}#mrHelpful .mrEyebrow{font-size:9px;font-weight:900;letter-spacing:.12em;color:#00e5ff;margin-bottom:5px}#mrHelpful .mrQuestion{font-size:15px;font-weight:900;line-height:1.25;margin:0 0 10px}#mrHelpful .mrActions{display:flex;gap:8px}#mrHelpful button{flex:1;border:1px solid #3b6a82;border-radius:9px;padding:10px 12px;background:#08263a;color:#edf8fb;font:inherit;font-size:12px;font-weight:850;cursor:pointer}#mrHelpful button[data-response="yes"]{background:#00e5ff;color:#02101d;border-color:#00e5ff}#mrHelpful .mrThanks{font-size:12px;color:#c3d1d8;line-height:1.4}@media(max-width:640px){#mrHelpful{bottom:12px}}`;
  document.head.appendChild(style);
  const box=document.createElement('aside');box.id='mrHelpful';box.setAttribute('aria-live','polite');box.innerHTML='<div class="mrEyebrow">QUICK CHECK</div><p class="mrQuestion">Did this help?</p><div class="mrActions"><button type="button" data-response="yes">Yes</button><button type="button" data-response="no">Not yet</button></div>';document.body.appendChild(box);
  let shown=false,done=false;
  const show=()=>{if(shown||done)return;shown=true;requestAnimationFrame(()=>box.classList.add('mrShow'))};
  const maybeShow=()=>{const doc=document.documentElement,max=Math.max(1,doc.scrollHeight-innerHeight);if(scrollY/max>=.28)show()};
  addEventListener('scroll',maybeShow,{passive:true});setTimeout(show,8000);
  box.addEventListener('click',e=>{const b=e.target?.closest?.('button[data-response]');if(!b||done)return;done=true;const response=b.dataset.response==='yes'?'yes':'no';try{localStorage.setItem(key,response)}catch{}const payload={event_name:'helpfulness_response',path,session_id:session,referrer_host:referrerHost,utm_source:qs.get('utm_source'),utm_medium:qs.get('utm_medium'),utm_campaign:qs.get('utm_campaign'),destination:path,target_type:'surface',target_id:surface,response,surface};try{fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload),keepalive:true,credentials:'omit'}).catch(()=>{})}catch{}box.innerHTML=`<div class="mrEyebrow">THANK YOU</div><div class="mrThanks">${response==='yes'?'Good — we’ll keep improving this.':'Got it — that tells us where to focus next.'}</div>`;setTimeout(()=>{box.classList.remove('mrShow');setTimeout(()=>box.remove(),220)},1400)});
})();