(()=>{
'use strict';
if(document.getElementById('mrLifestyleNav'))return;
const style=document.createElement('style');style.id='mrLifestyleNavStyle';style.textContent=`
#mrLifestyleNav{display:none}.mr-embed-frame{width:100%;height:900px;border:0;border-radius:14px;background:#02101d}.mr-embed-note{border-left:3px solid #00e5ff;background:#071d2c;color:#9fb3bd;padding:10px 12px;font-size:10px;line-height:1.45;margin-bottom:12px}.mrDirections{display:inline-flex;align-items:center;justify-content:center;gap:5px;border:1px solid #2f7c91;background:#073047;color:#c9f6ff!important;border-radius:8px;padding:8px 10px;font-size:9px;font-weight:900;text-decoration:none;white-space:nowrap}.mrDirections:hover{border-color:#00e5ff}.mrDirections:focus-visible{outline:2px solid #ffd36d;outline-offset:2px}
@media(max-width:700px){body{padding-bottom:78px}#mrLifestyleNav{position:fixed;left:10px;right:10px;bottom:max(10px,env(safe-area-inset-bottom));z-index:9998;display:grid;grid-auto-flow:column;grid-auto-columns:minmax(62px,1fr);gap:4px;padding:6px;background:#03111ff2;border:1px solid #2c536a;border-radius:16px;box-shadow:0 12px 36px #0009;backdrop-filter:blur(14px);overflow-x:auto;overscroll-behavior-x:contain;scroll-snap-type:x proximity;scrollbar-width:none}#mrLifestyleNav::-webkit-scrollbar{display:none}#mrLifestyleNav a{min-width:0;padding:8px 3px;border-radius:10px;color:#9fb6c1;text-decoration:none;text-align:center;font-size:7px;font-weight:850;line-height:1.2;scroll-snap-align:center}#mrLifestyleNav a b{display:block;color:#f4f8fa;font-size:13px;margin-bottom:2px}#mrLifestyleNav a[aria-current=page]{background:#092b3b;color:#7defff;box-shadow:inset 0 0 0 1px #1e6078}#mrLifestyleNav a:focus-visible{outline:2px solid #ffd36d;outline-offset:2px}.mrDirections{min-height:42px;flex:1;min-width:120px;font-size:10px}}
`;document.head.appendChild(style);
const p=location.pathname.replace(/\/$/,'')||'/',params=new URLSearchParams(location.search),liveView=params.get('view');
const items=[
 {href:'/neighborhoods',icon:'⌂',label:'LIVE',match:['/neighborhoods']},
 {href:'/?view=events',icon:'♪',label:'EVENTS',match:['/events']},
 {href:'/?view=support',icon:'✚',label:'SUPPORT',match:['/support']},
 {href:'/medical',icon:'+',label:'CARE',match:['/medical']},
 {href:'/military-value',icon:'$',label:'SAVE',match:['/military-value']},
 {href:'/community',icon:'★',label:'REVIEWS',match:['/community']},
 {href:'/?view=cars',icon:'▣',label:'CARS',match:[]}
];
const nav=document.createElement('nav');nav.id='mrLifestyleNav';nav.setAttribute('aria-label','Mission Rated lifestyle navigation');
nav.innerHTML=items.map(x=>{const active=x.match.some(m=>p===m||p===m+'.html')||(p==='/'&&((x.label==='CARS'&&liveView==='cars')||(x.label==='SUPPORT'&&liveView==='support')||(x.label==='EVENTS'&&liveView==='events')));return `<a href="${x.href}"${active?' aria-current="page"':''}><b aria-hidden="true">${x.icon}</b>${x.label}</a>`}).join('');
document.body.appendChild(nav);
const current=nav.querySelector('[aria-current="page"]');if(current)requestAnimationFrame(()=>current.scrollIntoView({block:'nearest',inline:'center'}));
if(p==='/'){
 const row=document.querySelector('.tabrow'),main=document.querySelector('main.main');
 if(row&&main){
  const installView=({id,label,small,note,src})=>{
   if(document.querySelector(`[data-view="${id}"]`))return null;
   const tab=document.createElement('button');tab.className='tab';tab.dataset.view=id;tab.setAttribute('aria-selected','false');tab.textContent=label;row.appendChild(tab);
   const section=document.createElement('section');section.className='section';section.id=id;section.hidden=true;section.innerHTML=`<div class="head"><div><h2>${label}</h2><small>${small}</small></div></div><div class="mr-embed-note">${note}</div><iframe class="mr-embed-frame" title="Mission Rated ${label}" loading="eager" src="${src}"></iframe>`;main.appendChild(section);
   const activate=()=>{document.querySelectorAll('.tab').forEach(x=>{const active=x===tab;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active))});document.querySelectorAll('.section').forEach(s=>s.hidden=s.id!==id);const category=document.getElementById('category'),city=document.getElementById('city');if(category)category.disabled=true;if(city)city.disabled=true;history.replaceState(null,'',`/?view=${id}`)};
   tab.addEventListener('click',activate);return {tab,activate};
  };
  const events=installView({id:'events',label:'Events',small:'CONCERTS • FESTIVALS • FAMILY • SPORTS',note:'Source-backed special events across Hampton Roads. Dates, free admission and other claims are shown only when supported by the linked public source.',src:'/events.html?embedded=1'});
  const support=installView({id:'support',label:'Support',small:'FAMILY • MONEY • CAREER • MOVING • DEPLOYMENT',note:'Find authoritative military and family support resources without leaving Mission Rated Live. Every resource remains MR Building until Mission Rated has enough first-party evidence for its own score.',src:'/support.html?embedded=1'});
  const cars=installView({id:'cars',label:'Buy a Car',small:'DEALERS • SALESPEOPLE • DEAL CHECK',note:'Start with people worth buying from. Dealer ratings and sourced salesperson mentions stay separate from Mission Rated reputation; thin evidence remains MR Building.',src:'/buy-a-car.html?embedded=1'});
  if(liveView==='events')events?.activate();else if(liveView==='support')support?.activate();else if(liveView==='cars')cars?.activate();
 }
}
const dirKey=s=>String(s??'').trim().toLowerCase();
const finite=n=>Number.isFinite(Number(n));
const dirDest=x=>finite(x?.latitude)&&finite(x?.longitude)?`${Number(x.latitude)},${Number(x.longitude)}`:[x?.address_line1||x?.address,x?.city,x?.state,x?.postal_code].map(v=>String(v??'').trim()).filter(Boolean).join(', ')||[x?.name,x?.city,x?.state].map(v=>String(v??'').trim()).filter(Boolean).join(', ');
const dirUrl=x=>{const d=dirDest(x);return d?`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(d)}`:''};
const addDirections=(card,item)=>{if(!card||!item||card.querySelector('.mrDirections'))return;const href=dirUrl(item);if(!href)return;const a=document.createElement('a');a.className='mrDirections';a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.textContent='↗ Directions';a.setAttribute('aria-label',`Directions to ${item.name||'this location'}`);const links=card.querySelector('.links,.actions,.sources');if(links)links.appendChild(a);else card.appendChild(a)};
const applyDirections=(root,map)=>{if(!root)return;for(const card of root.querySelectorAll('.card')){const name=card.querySelector('h2,h3')?.textContent?.trim(),item=map.get(dirKey(name));if(item)addDirections(card,item)}};
(async()=>{try{const ROOT='https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/';const [e,m,d]=await Promise.allSettled([fetch(ROOT+'public-explore').then(r=>r.ok?r.json():null),fetch(ROOT+'public-medical').then(r=>r.ok?r.json():null),fetch(ROOT+'public-directions').then(r=>r.ok?r.json():null)]);const explore=e.status==='fulfilled'&&e.value?e.value:{},medical=m.status==='fulfilled'&&m.value?m.value:{},directions=d.status==='fulfilled'&&d.value?d.value:{};const locationBusinesses=new Map((directions.businesses||[]).map(x=>[dirKey(x.name),x])),locationInstallations=new Map((directions.installations||[]).map(x=>[dirKey(x.name),x]));const districtById=new Map((explore.schools||[]).map(x=>[x.id,x]));const bm=new Map((explore.businesses||[]).map(x=>[dirKey(x.name),{...x,...(locationBusinesses.get(dirKey(x.name))||{})}])),im=new Map((explore.installations||[]).map(x=>[dirKey(x.name),{...x,...(locationInstallations.get(dirKey(x.name))||{})}])),mm=new Map((medical.providers||[]).map(x=>[dirKey(x.name),{...x,...(locationBusinesses.get(dirKey(x.name))||{})}])),sm=new Map((explore.school_items||[]).map(x=>{const district=districtById.get(x.school_district_id)||{};return[dirKey(x.name),{...x,city:district.locality||district.name,state:'VA'}]}));const apply=()=>{if(p==='/'){applyDirections(document.getElementById('businessGrid'),bm);applyDirections(document.getElementById('baseGrid'),im);applyDirections(document.getElementById('schoolGrid'),sm)}if(p==='/medical'||p==='/medical.html')applyDirections(document.getElementById('grid'),mm);if(p==='/bases'||p==='/bases.html')applyDirections(document.getElementById('grid'),im);if(p==='/schools'||p==='/schools.html')applyDirections(document.getElementById('groups'),sm);if(p==='/business'||p==='/business.html'){const item=bm.get(dirKey(document.getElementById('name')?.textContent));if(item)addDirections(document.querySelector('#content .card'),item)}if(p==='/installation'||p==='/installation.html'){const item=im.get(dirKey(document.querySelector('h1')?.textContent));if(item)addDirections(document.querySelector('.card'),item)}if(p==='/school'||p==='/school.html'){const item=sm.get(dirKey(document.getElementById('name')?.textContent));if(item)addDirections(document.querySelector('#grid .card'),item)}};apply();let n=0;const t=setInterval(()=>{apply();if(++n>18)clearInterval(t)},350)}catch{}})();
})();