(()=>{
'use strict';
if(location.pathname!=='/'&&location.pathname!=='/index.html')return;
function run(){
 const sub=document.querySelector('.hero .sub');if(sub)sub.textContent='Live better. Get support. Save more.';
 const p=document.querySelector('.hero p');if(p)p.textContent='Military lifestyle intelligence for everyday life: trusted places, verified savings, medical care, schools, installation support, neighborhoods, events, community reviews, and car-buying help. Mission Rated never invents a score when evidence is thin.';
 const eyebrow=document.querySelector('.hero .eyebrow');if(eyebrow)eyebrow.textContent='HAMPTON ROADS • LIVE • SUPPORT • SAVE';
 const hero=document.querySelector('.hero .wrap,.hero');
 if(hero&&!document.getElementById('mrHeadlineEvents')){
   const box=document.createElement('section');box.id='mrHeadlineEvents';box.setAttribute('aria-label','Headline Hampton Roads events');box.innerHTML='<div class="mrEventTop"><div><span class="mrEventEyebrow">🔥 HEADLINE EVENTS</span><b>Big things happening in Hampton Roads</b><span>Concerts, air shows and major limited-time events get priority.</span></div><a href="/events">See all events →</a></div><div class="mrEventRail"><a class="mrEventHero" href="/events"><strong>Miranda Lambert + Teddy Swims</strong><span>AUG 29 • OPERATION MWR • NAVAL STATION NORFOLK</span><em>Major military concert →</em></a><a class="mrEventHero" href="/events"><strong>NAS Oceana Air Show</strong><span>SEP 19–20 • BLUE ANGELS • FREE ADMISSION</span><em>Major Hampton Roads event →</em></a><a class="mrEventHero" href="/events"><strong>Farm Aid 2026</strong><span>SEP 26 • VIRGINIA BEACH</span><em>Willie Nelson • Neil Young • Dave Matthews + more →</em></a></div>';
   const anchor=hero.querySelector('.search');hero.insertBefore(box,anchor||null);
 }
 const links=document.querySelector('.hero .viewlinks');if(links){
   const wanted=[['/events','🔥 Headline Events'],['/medical','Medical / TRICARE'],['/?view=support','Support'],['/?view=cars','Buy a Car'],['/community','Community Reviews'],['/neighborhoods','Neighborhoods'],['/sources','Trust & Sources']];
   for(const [href,label] of wanted){if(![...links.querySelectorAll('a')].some(a=>a.getAttribute('href')===href)){const a=document.createElement('a');a.href=href;a.textContent=label+' ↗';links.appendChild(a)}}
 }
 if(hero&&!document.getElementById('mrGrowthShare')){const box=document.createElement('div');box.id='mrGrowthShare';box.innerHTML='<div><b>Know a military family in Hampton Roads?</b><span>Send them Mission Rated — the fastest way to help the community grow.</span></div><button id="mrShareAction" type="button">↗ Share Mission Rated</button>';hero.appendChild(box);const btn=box.querySelector('#mrShareAction');btn.addEventListener('click',async()=>{const url=new URL(location.href);url.searchParams.set('utm_source','share');url.searchParams.set('utm_medium','referral');url.searchParams.set('utm_campaign','community_growth');const data={title:'Mission Rated',text:'Military-friendly places, savings, schools, medical care, events, and local support in Hampton Roads.',url:url.toString()};try{if(navigator.share){await navigator.share(data);btn.textContent='✓ Shared';return}await navigator.clipboard.writeText(data.url);btn.textContent='✓ Link copied'}catch{try{await navigator.clipboard.writeText(data.url);btn.textContent='✓ Link copied'}catch{btn.textContent='Copy link unavailable'}}setTimeout(()=>btn.textContent='↗ Share Mission Rated',2200)})}
 const tabrow=document.querySelector('.tabrow');let carTab=document.querySelector('.tab[data-view="cars"]');if(tabrow&&!carTab){carTab=document.createElement('button');carTab.className='tab';carTab.dataset.view='cars';carTab.setAttribute('aria-selected','false');carTab.textContent='Buy a Car';tabrow.appendChild(carTab)}
 const main=document.querySelector('main.main');let carSection=document.getElementById('cars');if(main&&!carSection){carSection=document.createElement('section');carSection.className='section';carSection.id='cars';carSection.hidden=true;carSection.innerHTML='<div class="head"><div><h2>Buy a Car</h2><small>DEALERS • SALESPEOPLE • DEAL CHECK</small></div></div><div class="context">Car buying is part of Mission Rated Live. Dealer ratings and community signals stay source-attributed and separate from Mission Rated scores.</div><iframe id="mrCarFrame" title="Mission Rated Buy a Car" loading="lazy" src="/buy-a-car.html?embedded=1" style="width:100%;min-height:900px;border:0;border-radius:12px;background:#02101d" referrerpolicy="strict-origin-when-cross-origin"></iframe>';main.appendChild(carSection)}
 const activateCars=()=>{document.querySelectorAll('.tab').forEach(x=>{const active=x===carTab;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active))});document.querySelectorAll('.section').forEach(s=>s.hidden=s.id!=='cars');const category=document.getElementById('category'),city=document.getElementById('city');if(category)category.disabled=true;if(city)city.disabled=true;try{const u=new URL(location.href);u.searchParams.set('view','cars');history.replaceState(history.state,'',u)}catch{}};if(carTab)carTab.addEventListener('click',activateCars);window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='mr-car-height')return;const frame=document.getElementById('mrCarFrame');if(frame&&Number(e.data.height)>0)frame.style.height=Math.max(700,Number(e.data.height))+'px'});if(new URLSearchParams(location.search).get('view')==='cars')activateCars();
 const style=document.createElement('style');style.textContent='#mrHeadlineEvents{margin:18px 0 4px;padding:14px;border:1px solid #8b6a2d;border-radius:14px;background:linear-gradient(135deg,#241b13,#071d2c 65%);box-shadow:0 12px 35px #0005}.mrEventTop{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:10px}.mrEventTop b,.mrEventTop span{display:block}.mrEventTop b{font-size:17px;margin:3px 0}.mrEventTop span:not(.mrEventEyebrow){font-size:9px;color:#aebfc7}.mrEventEyebrow{font-size:9px!important;color:#ffd36d!important;font-weight:950;letter-spacing:.12em}.mrEventTop a{color:#00e5ff;text-decoration:none;font-size:9px;font-weight:900;white-space:nowrap}.mrEventRail{display:grid;grid-template-columns:1.3fr 1fr 1fr;gap:8px}.mrEventHero{display:flex;flex-direction:column;min-height:112px;padding:12px;border:1px solid #4c5660;border-radius:10px;background:#061b2de8;text-decoration:none}.mrEventHero:first-child{border-color:#b18a37;background:linear-gradient(145deg,#332515,#08263a)}.mrEventHero strong{font-size:14px;color:#fff}.mrEventHero span{margin-top:5px;font-size:8px;color:#ffd36d;font-weight:900}.mrEventHero em{margin-top:auto;padding-top:10px;font-size:8px;color:#8defff;font-style:normal}#mrGrowthShare{margin:18px 0 0;padding:13px 14px;border:1px solid #31566b;border-radius:12px;background:linear-gradient(135deg,#082235,#061923);display:flex;align-items:center;justify-content:space-between;gap:14px}#mrGrowthShare b{display:block;font-size:12px;color:#f4f8fa;margin-bottom:3px}#mrGrowthShare span{display:block;font-size:9px;line-height:1.45;color:#9fb6c1}#mrShareAction{appearance:none;border:1px solid #1e8aa1;background:#07384b;color:#c8f8ff;border-radius:9px;padding:10px 13px;font-size:9px;font-weight:900;white-space:nowrap;cursor:pointer}#mrShareAction:hover{border-color:#00e5ff}@media(max-width:640px){.mrEventTop{align-items:flex-start}.mrEventRail{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:4px}.mrEventHero{min-width:82%;scroll-snap-align:start}.viewlinks{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px!important}.viewlinks a{display:flex;align-items:center;justify-content:center;min-height:40px;padding:8px;border:1px solid #31566b;border-radius:9px;background:#061b2d;text-align:center}#mrGrowthShare{align-items:stretch;flex-direction:column}#mrShareAction{min-height:44px;font-size:10px;width:100%}#mrCarFrame{min-height:1100px!important}}';document.head.appendChild(style)
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();