(async()=>{
'use strict';
const {SUPABASE_FUNCTIONS_ROOT}=await import('/lib/config.js');
const API=SUPABASE_FUNCTIONS_ROOT+'public-medical';
let providers=new Map();
const safe=u=>/^https:\/\//i.test(String(u||''))?String(u):'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function css(){if(document.getElementById('mrMedicalBadgeStyle'))return;const s=document.createElement('style');s.id='mrMedicalBadgeStyle';s.textContent='.mrTricare{border-color:#236f61!important;color:#8affdc!important;background:#08251f!important}.mrNetwork{border-color:#6b5d39!important;color:#ffd98d!important}.mrMedicalFilter{border:1px solid #236f61;background:#08251f;color:#8affdc;border-radius:999px;padding:8px 11px;font-size:9px;font-weight:900;cursor:pointer;margin-top:8px}.mrMedicalEvidence{color:#8affdc!important}';document.head.appendChild(s)}
function normalizeRows(j){const rows=Array.isArray(j)?j:Array.isArray(j?.providers)?j.providers:Array.isArray(j?.businesses)?j.businesses:[];providers=new Map(rows.filter(x=>x?.name).map(x=>[String(x.name).trim(),x]));}
function addFilter(){if(location.pathname!=='/'||document.getElementById('mrMedicalFilter'))return;const stats=document.querySelector('.stats');if(!stats)return;const b=document.createElement('button');b.id='mrMedicalFilter';b.className='mrMedicalFilter';b.type='button';b.textContent='✚ TRICARE care';b.title='Show source-backed Medical providers with TRICARE acceptance evidence';b.onclick=()=>{const cat=document.getElementById('category');if(cat){cat.value='Medical';cat.dispatchEvent(new Event('change',{bubbles:true}));document.getElementById('places')?.scrollIntoView({behavior:'smooth',block:'start'});}};stats.insertAdjacentElement('afterend',b)}
function evidenceFor(x){return x?.tricare_evidence||x?.health_plan_evidence||x?.tricare||null}
function decorateCard(card){const name=card.querySelector('h2,h3')?.textContent?.trim();if(!name)return;const x=providers.get(name);if(!x||card.dataset.mrTricare==='1')return;const ev=evidenceFor(x),source=safe(ev?.source_url||x.tricare_source_url||x.source_url);const badges=card.querySelector('.badges')||card.querySelector('h2,h3');if(badges){const wrap=document.createElement('span');wrap.innerHTML='<span class="badge mrTricare">TRICARE Accepted</span> <span class="badge mrNetwork">Network status: confirm</span>';while(wrap.firstChild)badges.appendChild(wrap.firstChild)}const links=card.querySelector('.links');if(links&&source){const a=document.createElement('a');a.className='source mrMedicalEvidence';a.href=source;a.target='_blank';a.rel='noopener noreferrer';a.textContent='TRICARE evidence ↗';links.appendChild(a)}card.dataset.mrTricare='1'}
function decorateDetail(){const h=document.querySelector('h1');if(!h)return;const name=h.textContent?.trim(),x=providers.get(name);if(!x||document.body.dataset.mrTricare==='1')return;const ev=evidenceFor(x),source=safe(ev?.source_url||x.tricare_source_url||x.source_url);const host=h.parentElement||document.body;const box=document.createElement('div');box.className='badges';box.innerHTML='<span class="badge mrTricare">TRICARE Accepted</span><span class="badge mrNetwork">Network status: confirm</span>'+(source?`<a class="source mrMedicalEvidence" href="${esc(source)}" target="_blank" rel="noopener noreferrer">TRICARE evidence ↗</a>`:'');host.insertBefore(box,h.nextSibling);document.body.dataset.mrTricare='1'}
function render(){addFilter();document.querySelectorAll('#businessGrid .card').forEach(decorateCard);if(/\/business(?:\.html)?$/.test(location.pathname))decorateDetail()}
async function run(){css();try{const r=await fetch(API,{headers:{accept:'application/json'}});if(!r.ok)return;normalizeRows(await r.json())}catch{return}render();let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;render()})}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();