(()=>{
'use strict';
const ROOT='https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=u=>/^https:\/\//i.test(String(u||''))?String(u):'';
const day=v=>v?String(v).slice(0,10):'';
const pct=v=>v==null?'':`${Math.round(Number(v)*100)}% confidence`;
function css(){if(document.getElementById('mr-provenance-style'))return;const s=document.createElement('style');s.id='mr-provenance-style';s.textContent='.mrProvenance{margin-top:9px;padding-top:8px;border-top:1px dashed #27495b;font-size:8px;line-height:1.45;color:#849da8}.mrProvenance b{color:#b9ccd5}.mrProvenance a{color:#00e5ff;text-decoration:none}.mrProvenance .pending{color:#c7a96c}.mrDataStamp{display:inline-block;margin-left:7px;color:#6f8994;font-size:8px}';document.head.appendChild(s)}
function name(card){return card.querySelector('h2,h3')?.textContent?.trim()||''}
function add(card,html){if(card.querySelector('.mrProvenance'))return;const d=document.createElement('div');d.className='mrProvenance';d.innerHTML=html;card.appendChild(d)}
function businessHtml(x){const src=safe(x.source_url),rating=x.public_rating,rs=safe(rating?.source_url);let parts=[];if(x.provenance_status==='sourced'){parts.push(`<b>Business intel:</b> sourced${x.source_freshness?` • ${esc(x.source_freshness)}`:''}`)}else parts.push('<span class="pending">Business source pending</span>');if(rating){parts.push(`<b>Public rating provenance:</b> ${esc(rating.source_name||'external source')}${rating.observed_at?` • observed ${esc(day(rating.observed_at))}`:''}${rating.confidence!=null?` • ${esc(pct(rating.confidence))}`:''}${rs?` • <a href="${esc(rs)}" target="_blank" rel="noopener noreferrer">source ↗</a>`:''}`)}else if(src){parts.push(`<a href="${esc(src)}" target="_blank" rel="noopener noreferrer">intel source ↗</a>`)}return parts.join('<br>')}
function schoolHtml(x){const u=safe(x.source_url||x.official_profile_url),parts=[];parts.push(`<b>School provenance:</b> ${esc(x.source_name||'authoritative source')}${x.observed_at?` • observed ${esc(day(x.observed_at))}`:''}${x.confidence!=null?` • ${esc(pct(x.confidence))}`:''}`);if(u)parts.push(`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">open school source ↗</a>`);else parts.push('<span class="pending">Direct source link pending</span>');return parts.join('<br>')}
function baseHtml(x,r){const s=x.school_liaison||x.pcs_support||x.latest_signal,parts=[];if(s){parts.push(`<b>Installation provenance:</b> ${esc(s.source_name||s.source_type||'source')}${s.observed_at?` • observed ${esc(day(s.observed_at))}`:''}${s.confidence!=null?` • ${esc(pct(s.confidence))}`:''}`);const u=safe(s.source_url);if(u)parts.push(`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">open installation source ↗</a>`)}else parts.push('<span class="pending">Installation source pending</span>');if(r){const ru=safe(r.source_url);parts.push(`<b>Public rating provenance:</b> ${esc(r.source_name||'external source')}${r.observed_at?` • observed ${esc(day(r.observed_at))}`:''}${ru?` • <a href="${esc(ru)}" target="_blank" rel="noopener noreferrer">source ↗</a>`:''}`)}return parts.join('<br>')}
async function run(){css();try{const [e,r]=await Promise.all([fetch(ROOT+'public-explore',{headers:{accept:'application/json'}}),fetch(ROOT+'public-installation-ratings',{headers:{accept:'application/json'}})]);if(!e.ok)return;const j=await e.json(),rj=r.ok?await r.json():{};const businesses=new Map((j.businesses||[]).map(x=>[x.name,x])),schools=new Map((j.school_items||[]).map(x=>[x.name,x])),bases=new Map((j.installations||[]).map(x=>[x.name,x])),ratings=new Map((rj.installations||[]).filter(x=>x.best_public_rating).map(x=>[x.installation_id,x.best_public_rating]));const path=location.pathname;let type=path.includes('military-value')?'business':path.includes('schools')?'school':path.includes('bases')?'installation':'';if(!type)return;let attempts=0;const decorate=()=>{for(const card of document.querySelectorAll('.card')){const n=name(card);if(!n)continue;if(type==='business'){const x=businesses.get(n);if(x)add(card,businessHtml(x))}if(type==='school'){const x=schools.get(n);if(x)add(card,schoolHtml(x))}if(type==='installation'){const x=bases.get(n);if(x)add(card,baseHtml(x,ratings.get(x.id)))}}if(++attempts>12)clearInterval(timer)};decorate();const timer=setInterval(decorate,350);const status=document.getElementById('status');if(status&&j.meta?.generated_at){const span=document.createElement('span');span.className='mrDataStamp';span.textContent=`• data ${day(j.meta.generated_at)}`;status.appendChild(span)}}catch{}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
