(()=>{
'use strict';
const ROOT='https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/';
const EXPLORE=ROOT+'public-explore',VOTES=ROOT+'public-quick-rank-votes',SUBMIT=ROOT+'quick-rank-vote';
let data=null,votes=new Map();
const key=(t,id)=>`${t}:${id}`;
const voter=()=>{let k=localStorage.getItem('mr_quick_voter');if(!k){k=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem('mr_quick_voter',k)}return k};
function css(){if(document.getElementById('mr-quick-style'))return;const s=document.createElement('style');s.id='mr-quick-style';s.textContent='.mrQuick{display:flex;align-items:center;gap:5px;margin-left:auto;padding:5px;border:1px solid #31566b;border-radius:999px;background:#03131f}.mrVote{border:0;background:#0a2636;min-width:42px;height:31px;padding:0 8px;border-radius:999px;font-size:12px;font-weight:950;cursor:pointer}.mrVote.up{color:#72f0b5}.mrVote.down{color:#ff9292}.mrVote:focus-visible{outline:2px solid #00e5ff;outline-offset:1px}.mrVote:disabled{opacity:.45}.mrHeroScore{justify-content:space-between}.mrQuickLabel{font-size:8px;color:#8fa6b0;white-space:nowrap}';document.head.appendChild(s)}
function itemMap(type){const src=type==='business'?data?.businesses:type==='school'?data?.school_items:data?.installations;return new Map((src||[]).map(x=>[String(x.name||'').trim(),x]));}
function groups(){const p=location.pathname;if(p.endsWith('/military-value.html'))return [[document.getElementById('grid'),'business']];if(p.endsWith('/schools.html'))return [[document.getElementById('groups'),'school']];if(p.endsWith('/bases.html'))return [[document.getElementById('grid'),'installation']];return [[document.getElementById('businessGrid'),'business'],[document.getElementById('schoolGrid'),'school'],[document.getElementById('baseGrid'),'installation']];}
function render(){for(const [root,type] of groups()){if(!root)continue;const items=itemMap(type);for(const card of root.querySelectorAll('.card')){const name=card.querySelector('h2,h3')?.textContent?.trim(),item=items.get(name);if(!item)continue;const v=votes.get(key(type,item.id))||{up:0,down:0,net:0,total:0};let q=card.querySelector('.mrQuick');if(!q){q=document.createElement('div');q.className='mrQuick';card.querySelector('.mrHeroScore')?.appendChild(q)}q.innerHTML=`<span class="mrQuickLabel">Quick feedback</span><button class="mrVote up" aria-label="Positive quick feedback for ${name.replace(/[<>\"]/g,'')}">▲ ${v.up||0}</button><button class="mrVote down" aria-label="Negative quick feedback for ${name.replace(/[<>\"]/g,'')}">▼ ${v.down||0}</button>`;q.querySelector('.up')?.addEventListener('click',e=>submit(type,item.id,1,e.currentTarget));q.querySelector('.down')?.addEventListener('click',e=>submit(type,item.id,-1,e.currentTarget));card.querySelector('.mrQuickNote')?.remove();}}}
async function submit(type,id,dir,btn){const box=btn.closest('.mrQuick');box?.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await fetch(SUBMIT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_type:type,item_id:id,vote:dir,voter_key:voter()})});if(!r.ok)throw Error(r.status);const v=await r.json();votes.set(key(type,id),v);render()}catch{box?.setAttribute('title','Could not save quick feedback. Try again.')}finally{box?.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function run(){css();try{const [a,b]=await Promise.all([fetch(EXPLORE),fetch(VOTES)]);if(!a.ok)return;data=await a.json();if(b.ok){const j=await b.json();votes=new Map((j.votes||[]).map(v=>[key(v.item_type,v.item_id),v]))}}catch{return}let n=0,t=setInterval(()=>{render();if(++n>12)clearInterval(t)},350);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
