(()=>{
'use strict';
const ROOT='https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/';
const EXPLORE=ROOT+'public-explore',VOTES=ROOT+'public-quick-rank-votes',SUBMIT=ROOT+'quick-rank-vote';
let data=null,votes=new Map();
const key=(t,id)=>`${t}:${id}`;
const voter=()=>{let k=localStorage.getItem('mr_quick_voter');if(!k){k=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem('mr_quick_voter',k)}return k};
const selection=(t,id)=>Number(localStorage.getItem(`mr_vote_${key(t,id)}`)||0);
function css(){if(document.getElementById('mr-quick-style'))return;const s=document.createElement('style');s.id='mr-quick-style';s.textContent='.mrQuick{display:flex;align-items:center;gap:7px;margin-top:10px;padding:7px;border:1px solid #31566b;border-radius:10px;background:#03131f}.mrVote{border:1px solid #31566b;background:#0a2636;min-width:58px;height:36px;padding:0 10px;border-radius:9px;font-size:13px;font-weight:950;cursor:pointer}.mrVote.up{color:#72f0b5}.mrVote.down{color:#ff9292}.mrVote:focus-visible{outline:2px solid #00e5ff;outline-offset:1px}.mrVote:disabled{opacity:.45}.mrVote[aria-pressed="true"]{border-color:#00e5ff;box-shadow:0 0 0 1px #00e5ff inset}.mrQuickLabel{font-size:9px;color:#b8c8cf;margin-right:auto;line-height:1.25}.mrQuickNote{font-size:7px;color:#78929e;margin-top:4px;line-height:1.35}@media(max-width:640px){.mrQuick{width:100%;padding:8px}.mrVote{min-width:62px;height:42px;font-size:14px}.mrQuickLabel{font-size:10px}.mrQuickNote{font-size:8px}}';document.head.appendChild(s)}
function source(type){return type==='business'?data?.businesses:type==='school'?data?.school_items:data?.installations}
function itemMap(type){return new Map((source(type)||[]).map(x=>[String(x.name||'').trim(),x]))}
function groups(){const p=location.pathname;if(/\/military-value(?:\.html)?$/.test(p))return [[document.getElementById('grid'),'business']];if(/\/schools(?:\.html)?$/.test(p))return [[document.getElementById('groups'),'school']];if(/\/bases(?:\.html)?$/.test(p))return [[document.getElementById('grid'),'installation']];return [[document.getElementById('businessGrid'),'business'],[document.getElementById('schoolGrid'),'school'],[document.getElementById('baseGrid'),'installation']]}
function prompt(type){return type==='business'?'Been here?':type==='school'?'Family experience?':'Stationed here?'}
function attach(card,type,item){if(!card||!item)return;const name=String(item.name||'this item'),v=votes.get(key(type,item.id))||{up:0,down:0,net:0,total:0},mine=selection(type,item.id);let q=card.querySelector('.mrQuick');if(!q){q=document.createElement('div');q.className='mrQuick';const target=card.querySelector('.mrHeroScore,.badges')||card.querySelector('h2,h3');if(target?.classList?.contains('mrHeroScore'))target.appendChild(q);else if(target)target.insertAdjacentElement('afterend',q);else card.prepend(q)}q.innerHTML=`<span class="mrQuickLabel">${prompt(type)}<br>Rate your experience</span><button class="mrVote up" aria-label="Recommend ${name.replace(/[<>\"]/g,'')}" aria-pressed="${mine===1}">▲ ${v.up||0}</button><button class="mrVote down" aria-label="Do not recommend ${name.replace(/[<>\"]/g,'')}" aria-pressed="${mine===-1}">▼ ${v.down||0}</button>`;q.querySelector('.up')?.addEventListener('click',e=>submit(type,item.id,1,e.currentTarget));q.querySelector('.down')?.addEventListener('click',e=>submit(type,item.id,-1,e.currentTarget));let note=card.querySelector('.mrQuickNote');if(!note){note=document.createElement('div');note.className='mrQuickNote';q.insertAdjacentElement('afterend',note)}note.textContent='Community signal only • does not create an MR score or User Verified badge.'}
function renderDetail(){const p=location.pathname,m=p.match(/\/(business|school|installation)(?:\.html)?$/);if(!m)return false;const type=m[1],id=new URLSearchParams(location.search).get('id'),item=(source(type)||[]).find(x=>String(x.id)===String(id));if(!item)return true;attach(document.querySelector('#content .card,.main .card'),type,item);return true}
function render(){if(renderDetail())return;for(const [root,type] of groups()){if(!root)continue;const items=itemMap(type);for(const card of root.querySelectorAll('.card')){const name=card.querySelector('h2,h3')?.textContent?.trim(),item=items.get(name);if(item)attach(card,type,item)}}}
async function submit(type,id,dir,btn){const box=btn.closest('.mrQuick');box?.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await fetch(SUBMIT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_type:type,item_id:id,vote:dir,voter_key:voter()})});if(!r.ok)throw Error(r.status);const v=await r.json();votes.set(key(type,id),v);localStorage.setItem(`mr_vote_${key(type,id)}`,String(dir));render()}catch{box?.setAttribute('title','Could not save quick feedback. Try again.')}finally{box?.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function run(){css();try{const [a,b]=await Promise.all([fetch(EXPLORE),fetch(VOTES)]);if(!a.ok)return;data=await a.json();if(b.ok){const j=await b.json();votes=new Map((j.votes||[]).map(v=>[key(v.item_type,v.item_id),v]))}}catch{return}let n=0,t=setInterval(()=>{render();if(++n>18)clearInterval(t)},350);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
