(()=>{
'use strict';
const ROOT='https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/';
const EXPLORE=ROOT+'public-explore',VOTES=ROOT+'public-quick-rank-votes',SUBMIT=ROOT+'quick-rank-vote';
let data=null,votes=new Map();
const key=(t,id)=>`${t}:${id}`;
const voter=()=>{let k=localStorage.getItem('mr_quick_voter');if(!k){k=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem('mr_quick_voter',k)}return k};
const selection=(t,id)=>Number(localStorage.getItem(`mr_vote_${key(t,id)}`)||0);
function css(){if(document.getElementById('mr-quick-style'))return;const s=document.createElement('style');s.id='mr-quick-style';s.textContent='.mrQuick{display:flex;align-items:center;gap:7px;margin-top:10px;padding:7px;border:1px solid #31566b;border-radius:10px;background:#03131f}.mrVote{border:1px solid #31566b;background:#0a2636;min-width:58px;height:36px;padding:0 10px;border-radius:9px;font-size:13px;font-weight:950;cursor:pointer}.mrVote.up{color:#72f0b5}.mrVote.down{color:#ff9292}.mrVote:focus-visible{outline:2px solid #00e5ff;outline-offset:1px}.mrVote:disabled{opacity:.45}.mrVote[aria-pressed="true"]{border-color:#00e5ff;box-shadow:0 0 0 1px #00e5ff inset}.mrQuickLabel{font-size:9px;color:#b8c8cf;margin-right:auto;line-height:1.25}.mrQuickNote{font-size:7px;color:#78929e;margin-top:4px;line-height:1.35}.mrPriorityLink{text-decoration:none;display:inline-flex;align-items:center}.mrHolidayLink{border-color:#786627!important;color:#ffd36d!important;background:#211d0d!important}.search.mrSingleSearch{grid-template-columns:1fr}.mrDealNext{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:14px;padding:13px 14px;border:1px solid #31566b;border-radius:12px;background:#061b2d}.mrDealNextCopy{min-width:0}.mrDealNext strong{display:block;font-size:11px;color:#f5f8fa}.mrDealNext span{display:block;margin-top:3px;font-size:9px;line-height:1.35;color:#94aab4}.mrDealNextLinks{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.mrDealNext a{display:inline-flex;align-items:center;justify-content:center;text-decoration:none;border:1px solid #3b6a82;background:#08263a;color:#eaf5f8;border-radius:8px;padding:9px 11px;font-size:9px;font-weight:900}.mrDealNext a:first-child{border-color:#00e5ff;color:#02101d;background:#00e5ff}.mrDealNext a:focus-visible{outline:2px solid #00e5ff;outline-offset:2px}@media(max-width:640px){.mrQuick{width:100%;padding:8px}.mrVote{min-width:62px;height:42px;font-size:14px}.mrQuickLabel{font-size:10px}.mrQuickNote{font-size:8px}.mrDealNext{align-items:stretch;flex-direction:column}.mrDealNextLinks{display:grid;grid-template-columns:1fr 1fr}.mrDealNext a{min-height:42px}}';document.head.appendChild(s)}
function isHomepage(){const p=location.pathname;return p==='/'||/\/index\.html$/.test(p)}
function loadWeekendBrief(){if(!isHomepage()||document.getElementById('mrWeekendBrief')||document.querySelector('script[data-mr-weekend-brief]'))return;const s=document.createElement('script');s.src='/weekend-brief.js';s.defer=true;s.dataset.mrWeekendBrief='true';document.body.appendChild(s)}
function loadFeedback(){if(!isHomepage()||document.getElementById('mrFeedbackButton')||document.querySelector('script[data-mr-feedback]'))return;const s=document.createElement('script');s.src='/feedback.js';s.defer=true;s.dataset.mrFeedback='true';document.body.appendChild(s)}
function syncHomepageSearch(){if(!isHomepage())return;const active=document.querySelector('.tab[data-view].active'),search=document.querySelector('.search'),q=document.getElementById('q'),category=document.getElementById('category'),city=document.getElementById('city');if(!active||!search||!q||!category||!city)return;const view=active.dataset.view,places=view==='places';category.hidden=!places;city.hidden=!places;search.classList.toggle('mrSingleSearch',!places);q.placeholder=view==='deals'?"Search today's deals…":view==='schools'?'Search schools…':view==='bases'?'Search bases and PCS resources…':'Search places…';q.setAttribute('aria-label',q.placeholder.replace('…',''));}
function addDealNextStep(){if(!isHomepage()||document.getElementById('mrDealNext'))return;const deals=document.getElementById('deals'),grid=document.getElementById('dealGrid');if(!deals||!grid)return;const c=document.createElement('div');c.id='mrDealNext';c.className='mrDealNext';c.innerHTML='<div class="mrDealNextCopy"><strong>Keep saving after today.</strong><span>Browse more source-backed local military value, or jump to the Labor Day guide.</span></div><div class="mrDealNextLinks"><a href="/savings.html">Explore all savings →</a><a href="/labor-day.html">Labor Day →</a></div>';grid.insertAdjacentElement('afterend',c)}
function homepagePriority(){if(!isHomepage())return;const row=document.querySelector('.tabrow'),places=row?.querySelector('[data-view="places"]'),deals=row?.querySelector('[data-view="deals"]');if(!row||!places||!deals)return;deals.textContent="Today's Deals";const make=(label,href,extra='')=>{const a=document.createElement('a');a.className=`tab mrPriorityLink ${extra}`.trim();a.href=href;a.textContent=label;return a};if(!row.querySelector('[data-mr-priority="labor-day"]')){const labor=make('Labor Day','/labor-day.html','mrHolidayLink');labor.dataset.mrPriority='labor-day';const local=make('Local Deals','/savings.html');local.dataset.mrPriority='local-deals';const everyday=make('Everyday Deals','/military-value.html');everyday.dataset.mrPriority='everyday-deals';row.insertBefore(deals,row.firstChild);deals.insertAdjacentElement('afterend',labor);labor.insertAdjacentElement('afterend',local);local.insertAdjacentElement('afterend',everyday);everyday.insertAdjacentElement('afterend',places)}for(const tab of row.querySelectorAll('.tab[data-view]'))tab.addEventListener('click',()=>requestAnimationFrame(syncHomepageSearch));if(!deals.classList.contains('active'))deals.click();syncHomepageSearch();addDealNextStep()}
function source(type){return type==='business'?data?.businesses:type==='school'?data?.school_items:data?.installations}
function itemMap(type){return new Map((source(type)||[]).map(x=>[String(x.name||'').trim(),x]))}
function groups(){const p=location.pathname;if(/\/military-value(?:\.html)?$/.test(p))return [[document.getElementById('grid'),'business']];if(/\/medical(?:\.html)?$/.test(p))return [[document.getElementById('grid'),'business']];if(/\/schools(?:\.html)?$/.test(p))return [[document.getElementById('groups'),'school']];if(/\/bases(?:\.html)?$/.test(p))return [[document.getElementById('grid'),'installation']];return [[document.getElementById('businessGrid'),'business'],[document.getElementById('schoolGrid'),'school'],[document.getElementById('baseGrid'),'installation']]}
function prompt(type){return type==='business'?'Been here?':type==='school'?'Family experience?':'Stationed here?'}
function attach(card,type,item){if(!card||!item)return;const name=String(item.name||'this item'),v=votes.get(key(type,item.id))||{up:0,down:0,net:0,total:0},mine=selection(type,item.id);let q=card.querySelector('.mrQuick');if(!q){q=document.createElement('div');q.className='mrQuick';const target=card.querySelector('.mrHeroScore,.badges')||card.querySelector('h2,h3');if(target?.classList?.contains('mrHeroScore'))target.appendChild(q);else if(target)target.insertAdjacentElement('afterend',q);else card.prepend(q)}q.innerHTML=`<span class="mrQuickLabel">${prompt(type)}<br>Rate your experience</span><button class="mrVote up" aria-label="Recommend ${name.replace(/[<>\"]/g,'')}" aria-pressed="${mine===1}">▲ ${v.up||0}</button><button class="mrVote down" aria-label="Do not recommend ${name.replace(/[<>\"]/g,'')}" aria-pressed="${mine===-1}">▼ ${v.down||0}</button>`;q.querySelector('.up')?.addEventListener('click',e=>submit(type,item.id,1,e.currentTarget));q.querySelector('.down')?.addEventListener('click',e=>submit(type,item.id,-1,e.currentTarget));let note=card.querySelector('.mrQuickNote');if(!note){note=document.createElement('div');note.className='mrQuickNote';q.insertAdjacentElement('afterend',note)}note.textContent='Community signal only • does not create an MR score or User Verified badge.'}
function renderDetail(){const p=location.pathname,m=p.match(/\/(business|school|installation)(?:\.html)?$/);if(!m)return false;const type=m[1],id=new URLSearchParams(location.search).get('id'),item=(source(type)||[]).find(x=>String(x.id)===String(id));if(!item)return true;attach(document.querySelector('#content .card,.main .card'),type,item);return true}
function render(){if(renderDetail())return;for(const [root,type] of groups()){if(!root)continue;const items=itemMap(type);for(const card of root.querySelectorAll('.card')){const name=card.querySelector('h2,h3')?.textContent?.trim(),item=items.get(name);if(item)attach(card,type,item)}}}
async function submit(type,id,dir,btn){const box=btn.closest('.mrQuick');box?.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await fetch(SUBMIT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_type:type,item_id:id,vote:dir,voter_key:voter()})});if(!r.ok)throw Error(r.status);const v=await r.json();votes.set(key(type,id),v);localStorage.setItem(`mr_vote_${key(type,id)}`,String(dir));render()}catch{box?.setAttribute('title','Could not save quick feedback. Try again.')}finally{box?.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function run(){css();homepagePriority();loadWeekendBrief();loadFeedback();try{const [a,b]=await Promise.all([fetch(EXPLORE),fetch(VOTES)]);if(!a.ok)return;data=await a.json();if(b.ok){const j=await b.json();votes=new Map((j.votes||[]).map(v=>[key(v.item_type,v.item_id),v]))}}catch{return}let n=0,t=setInterval(()=>{render();if(++n>18)clearInterval(t)},350);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();