(()=>{
'use strict';
const ROOT='https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/';
const EXPLORE=ROOT+'public-explore',NEIGHBORHOODS=ROOT+'public-neighborhoods',REVIEWS=ROOT+'public-item-reviews',SUBMIT=ROOT+'submit-item-review';
let maps={business:new Map(),school:new Map(),installation:new Map(),neighborhood:new Map()},aggregates=new Map();
const key=(t,id)=>`${t}:${id}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function css(){if(document.getElementById('mr-review-style'))return;const s=document.createElement('style');s.id='mr-review-style';s.textContent='.mrReviewBar{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:10px;padding-top:9px;border-top:1px solid #244759}.mrReviewSummary{font-size:9px;color:#9fb3bd}.mrReviewSummary b{color:#ffd36d}.mrReviewBtn{border:1px solid #00bfd7;background:#062536;color:#91f7ff;border-radius:999px;padding:7px 10px;font-size:9px;font-weight:900;cursor:pointer}.mrReviewModal{position:fixed;inset:0;z-index:10020;background:#00101bd9;display:none;align-items:center;justify-content:center;padding:18px}.mrReviewModal.open{display:flex}.mrReviewPanel{width:min(560px,100%);max-height:90vh;overflow:auto;background:#061a29;border:1px solid #356278;border-radius:16px;padding:18px;box-shadow:0 24px 80px #0008}.mrReviewHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.mrReviewClose{border:0;background:#0d3042;color:white;border-radius:999px;width:32px;height:32px;font-size:17px}.mrReviewGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:14px}.mrReviewGrid label{font-size:9px;color:#9fb3bd}.mrReviewGrid select,.mrReviewGrid input,.mrReviewGrid textarea{width:100%;margin-top:4px;padding:10px;border:1px solid #355a6d;border-radius:8px;background:#031522;color:#fff}.mrReviewGrid textarea{min-height:90px;resize:vertical}.mrReviewWide{grid-column:1/-1}.mrReviewSubmit{width:100%;margin-top:12px;padding:11px;border:0;border-radius:9px;background:#00d6e8;color:#00141e;font-weight:950;cursor:pointer}.mrReviewNote{font-size:8px;color:#8fa6b0;line-height:1.45;margin-top:9px}.mrReviewStatus{font-size:9px;margin-top:8px;color:#84efc0}@media(max-width:560px){.mrReviewGrid{grid-template-columns:1fr}.mrReviewWide{grid-column:auto}}';document.head.appendChild(s)}
function ensureModal(){if(document.getElementById('mrReviewModal'))return;const d=document.createElement('div');d.id='mrReviewModal';d.className='mrReviewModal';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.innerHTML='<div class="mrReviewPanel"><div class="mrReviewHead"><div><div style="font-size:9px;color:#00e5ff;font-weight:900">MISSION RATED REVIEW</div><h2 id="mrReviewTitle" style="margin:5px 0">Rate this item</h2></div><button class="mrReviewClose" aria-label="Close review">×</button></div><form id="mrReviewForm"><input type="hidden" name="item_type"><input type="hidden" name="item_id"><div class="mrReviewGrid"><label>Overall rating<select name="overall_rating" required><option value="">Choose</option><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Mixed</option><option value="2">2 — Poor</option><option value="1">1 — Bad</option></select></label><label>Military-family fit<select name="military_family_fit"><option value="">Optional</option><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Value<select name="value_rating"><option value="">Optional</option><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Convenience<select name="convenience_rating"><option value="">Optional</option><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Would you recommend?<select name="would_recommend"><option value="">Optional</option><option value="true">Yes</option><option value="false">No</option></select></label><label>Military affiliation<input name="military_affiliation" maxlength="80" placeholder="Active duty, spouse, veteran…"></label><label>PCS / experience year<input name="pcs_year" inputmode="numeric" maxlength="4" placeholder="2026"></label><label class="mrReviewWide">Review title<input name="title" maxlength="120" placeholder="Optional quick summary"></label><label class="mrReviewWide">Comments<textarea name="body" maxlength="1800" placeholder="Optional — what should another military family know?"></textarea></label></div><button class="mrReviewSubmit" type="submit">Submit review</button><div class="mrReviewNote">No login required for beta submissions. Anonymous reviews enter <b>Pending / Unverified</b> moderation and do not receive a User Verified badge automatically.</div><div class="mrReviewStatus" id="mrReviewStatus" aria-live="polite"></div></form></div>';document.body.appendChild(d);d.querySelector('.mrReviewClose').onclick=()=>d.classList.remove('open');d.addEventListener('click',e=>{if(e.target===d)d.classList.remove('open')});d.querySelector('form').addEventListener('submit',submit)}
function pageGroups(){const p=location.pathname;if(p.includes('military-value'))return [[document.getElementById('grid'),'business']];if(p.includes('schools'))return [[document.getElementById('groups'),'school']];if(p.includes('bases'))return [[document.getElementById('grid'),'installation']];if(p.includes('neighborhoods'))return [[document.getElementById('grid'),'neighborhood']];return [[document.getElementById('businessGrid'),'business'],[document.getElementById('schoolGrid'),'school'],[document.getElementById('baseGrid'),'installation']];}
function resolve(type,card){const direct=card.dataset.itemId;if(direct)return {id:direct,name:card.querySelector('h2,h3')?.textContent?.trim()||'this item'};const name=card.querySelector('h2,h3')?.textContent?.trim();return maps[type].get(name)||null}
function decorate(){for(const [root,type] of pageGroups()){if(!root)continue;for(const card of root.querySelectorAll('.card')){const item=resolve(type,card);if(!item)continue;let bar=card.querySelector('.mrReviewBar');if(!bar){bar=document.createElement('div');bar.className='mrReviewBar';card.appendChild(bar)}const a=aggregates.get(key(type,item.id));bar.innerHTML=`<div class="mrReviewSummary">${a?`<b>${Number(a.average).toFixed(1)}/5</b> • ${a.count} MR review${a.count===1?'':'s'}${a.user_verified_count?` • ${a.user_verified_count} verified`:''}`:'No published MR reviews yet'}</div><button class="mrReviewBtn" type="button">Rate this</button>`;bar.querySelector('button').onclick=()=>open(type,item)}}}
function open(type,item){ensureModal();const m=document.getElementById('mrReviewModal'),f=document.getElementById('mrReviewForm');f.reset();f.elements.item_type.value=type;f.elements.item_id.value=item.id;document.getElementById('mrReviewTitle').textContent=`Rate ${item.name}`;document.getElementById('mrReviewStatus').textContent='';m.classList.add('open');f.elements.overall_rating.focus()}
async function submit(e){e.preventDefault();const f=e.currentTarget,b=Object.fromEntries(new FormData(f).entries());for(const k of ['overall_rating','military_family_fit','value_rating','convenience_rating','pcs_year'])if(b[k]!=='')b[k]=Number(b[k]);else delete b[k];if(b.would_recommend!=='')b.would_recommend=b.would_recommend==='true';else delete b.would_recommend;const status=document.getElementById('mrReviewStatus'),btn=f.querySelector('button[type=submit]');btn.disabled=true;status.textContent='Submitting…';try{const r=await fetch(SUBMIT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});if(!r.ok)throw Error(r.status);status.textContent='Submitted. Review is pending moderation.';setTimeout(()=>document.getElementById('mrReviewModal')?.classList.remove('open'),1100)}catch{status.textContent='Could not submit. Please try again.'}finally{btn.disabled=false}}
async function run(){css();ensureModal();try{const [e,n,r]=await Promise.all([fetch(EXPLORE),fetch(NEIGHBORHOODS),fetch(REVIEWS)]);const ej=e.ok?await e.json():{},nj=n.ok?await n.json():{},rj=r.ok?await r.json():{};maps.business=new Map((ej.businesses||[]).map(x=>[x.name,{id:x.id,name:x.name}]));maps.school=new Map((ej.school_items||[]).map(x=>[x.name,{id:x.id,name:x.name}]));maps.installation=new Map((ej.installations||[]).map(x=>[x.name,{id:x.id,name:x.name}]));maps.neighborhood=new Map((nj.neighborhoods||[]).map(x=>[x.name,{id:x.id,name:x.name}]));aggregates=new Map((rj.reviews||[]).map(x=>[key(x.item_type,x.item_id),x]))}catch{}let tries=0,t=setInterval(()=>{decorate();if(++tries>12)clearInterval(t)},350);decorate()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
