(()=>{
'use strict';
const grid=document.getElementById('grid');if(!grid)return;
const style=document.createElement('style');style.textContent='.supportSearch{display:grid;grid-template-columns:1fr auto auto;gap:7px;margin:0 0 12px}.supportSearch input{width:100%;padding:10px;border:1px solid #365e73;border-radius:9px;background:#031522;color:#fff}.supportSearch a{display:flex;align-items:center;text-decoration:none;border:1px solid #365e73;border-radius:9px;padding:0 10px;color:#bdeff5;font-size:9px;font-weight:850}.trustBadges{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.trustBadge{font-size:8px;font-weight:900;padding:4px 6px;border-radius:5px;border:1px solid #7b672f;color:#ffd36d;background:#1a1b17}.trustBadge.official{border-color:#167482;color:#80f1ff;background:#07323b}@media(max-width:620px){.supportSearch{grid-template-columns:1fr 1fr}.supportSearch input{grid-column:1/-1}}';document.head.appendChild(style);
const filters=document.querySelector('.filters');const box=document.createElement('div');box.className='supportSearch';box.innerHTML='<input id="supportQ" aria-label="Search military support" placeholder="Search support: childcare, money, jobs, moving…"><a href="/bases">Bases / PCS</a><a href="/schools">Schools</a>';filters?.parentNode?.insertBefore(box,filters);
for(const card of grid.querySelectorAll('.card')){const meta=card.querySelector('.meta');const authoritative=!!meta?.querySelector('.verified');const badges=document.createElement('div');badges.className='trustBadges';badges.innerHTML='<span class="trustBadge">MR Building</span>'+(authoritative?'<span class="trustBadge official">✓ Official Source Verified</span>':'');card.querySelector('.type')?.after(badges);if(authoritative){const v=meta.querySelector('.verified');if(v)v.textContent='OFFICIAL SOURCE VERIFIED'}}
let active='all';const q=document.getElementById('supportQ');function apply(){const term=(q?.value||'').toLowerCase().trim();for(const c of grid.querySelectorAll('.card')){const tags=(c.dataset.tags||'').split(' '),tagOk=active==='all'||tags.includes(active),textOk=!term||c.textContent.toLowerCase().includes(term);c.style.display=tagOk&&textOk?'block':'none'}}
q?.addEventListener('input',apply);document.querySelectorAll('[data-f]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.f||'all';apply()}));apply();
})();
