import { createClient } from 'npm:@supabase/supabase-js@2.95.0'
import { corsHeaders } from 'npm:@supabase/supabase-js@2.95.0/cors'
const day=(v:string|null)=>v?new Date(v).toISOString().slice(0,10):null
const hasHttps=(v:unknown)=>typeof v==='string'&&/^https:\/\//i.test(v)
const host=(v:unknown)=>{try{return hasHttps(v)?new URL(String(v)).hostname.replace(/^www\./,''):''}catch{return''}}
const officialBusinessSource=(website:unknown,source:unknown)=>{const sh=host(source),wh=host(website);return !!sh&&(sh.endsWith('.gov')||sh.endsWith('.mil')|| (!!wh&&(sh===wh||sh.endsWith('.'+wh))))}
const officialSchoolSource=(...values:unknown[])=>values.some(v=>{const h=host(v);return !!h&&(h.endsWith('.gov')||h.endsWith('.virginia.gov')||h==='virginia.gov')})
const dealWeight=(x:any)=>{const t=`${x.offer_value_text||''} ${x.title||''}`.toLowerCase();if(/free\b|100%/.test(t))return 100;const p=t.match(/(\d+(?:\.\d+)?)\s*%/);if(p)return Math.min(90,Number(p[1]));const d=t.match(/\$(\d+(?:\.\d+)?)/);if(d)return Math.min(80,Number(d[1])*2);return 10}
let memoryCache:string|null=null
let memoryCacheAt=0
const CACHE_MS=5*60*1000
const headers={...corsHeaders,'Content-Type':'application/json','Cache-Control':'public, max-age=60, s-maxage=300, stale-while-revalidate=86400'}
const ok=(data:any)=>new Response(typeof data==='string'?data:JSON.stringify(data),{headers})
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders})
 if(req.method!=='GET')return new Response(JSON.stringify({error:'method_not_allowed'}),{status:405,headers})
 if(memoryCache && Date.now()-memoryCacheAt<CACHE_MS)return ok(memoryCache)
 try{
  const secrets=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const secret=secrets.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!secret)throw new Error('missing_secret')
  const s=createClient(Deno.env.get('SUPABASE_URL')!,secret,{auth:{persistSession:false}});const nowIso=new Date().toISOString()
  const queries=[
   s.from('businesses').select('id,name,category,description,website_url,city,state,veteran_owned,military_spouse_owned,source_url,source_checked_at').eq('active',true).order('name').limit(160),
   s.from('deals').select('id,business_id,title,description,offer_value_text,terms,source_url,verified_at,ends_at,businesses(name,city,website_url)').eq('active',true).not('verified_at','is',null).or(`ends_at.is.null,ends_at.gte.${nowIso}`).order('verified_at',{ascending:false}).limit(60),
   s.from('school_districts').select('id,name,locality,official_profile_url,summary,confidence,observed_at').order('name').limit(40),
   s.from('installations').select('id,name,branch,city,state').eq('active',true).order('name').limit(40),
   s.from('school_district_signals').select('school_district_id,signal_key,signal_label,numeric_value,text_value,unit,source_name,source_url,observed_at,confidence').order('observed_at',{ascending:false}),
   s.from('installation_signals').select('installation_id,signal_key,signal_label,numeric_value,text_value,unit,source_name,source_url,source_type,observed_at,confidence').order('observed_at',{ascending:false}),
   s.from('schools').select('id,school_district_id,name,school_level,accreditation_status,performance_level,framework_score,official_profile_url,source_name,source_type,source_url,observed_at,confidence,mission_score,mission_score_status,purple_star_status,purple_star_source_url,purple_star_observed_at').eq('active',true).order('framework_score',{ascending:false}),
   s.from('business_scores').select('business_id,review_count,raw_score,mission_score'),
   s.from('business_signals').select('business_id,signal_type,source_name,source_type,source_url,rating,rating_scale,sample_size,signal_text,confidence,observed_at').eq('signal_type','public_review_rating').order('observed_at',{ascending:false}),
   s.from('item_verifications').select('target_type,target_id,verification_type,status,source_url,verified_at').eq('status','verified')
  ]
  const [b,d,sc,i,ss,isig,si,bs,bsg,v]=await Promise.all(queries)
  for(const x of [b,d,sc,i,ss,isig,si,bs]) if(x.error) throw x.error
  const optionalErrors=[bsg.error?'business_signals':null,v.error?'item_verifications':null].filter(Boolean)
  const ver=new Map<string,any[]>();for(const x of v.data||[]){const k=`${x.target_type}:${x.target_id}`,a=ver.get(k)||[];a.push(x);ver.set(k,a)}
  const sb=new Map<string,any[]>();for(const x of ss.data||[]){const a=sb.get(x.school_district_id)||[];a.push(x);sb.set(x.school_district_id,a)}
  const ib=new Map<string,any[]>();for(const x of isig.data||[]){const a=ib.get(x.installation_id)||[];a.push(x);ib.set(x.installation_id,a)}
  const scoreBy=new Map((bs.data||[]).map((x:any)=>[x.business_id,x]));const ratingBy=new Map<string,any>();for(const x of bsg.data||[])if(!ratingBy.has(x.business_id))ratingBy.set(x.business_id,x)
  const rawDeals=d.data||[],sourceBackedDeals=rawDeals.filter((x:any)=>hasHttps(x.source_url));const dealBy=new Map<string,any[]>();for(const x of sourceBackedDeals){const a=dealBy.get(x.business_id)||[];a.push(x);dealBy.set(x.business_id,a)}
  const districts=(sc.data||[]).map((x:any)=>{const a=sb.get(x.id)||[],sig=a[0],purple=a.find((y:any)=>/purple/i.test(String(y.signal_key)+' '+String(y.signal_label)));return{...x,signal_count:a.length,purple_star:purple?{label:purple.signal_label,text:purple.text_value,value:purple.numeric_value,source_name:purple.source_name,source_url:purple.source_url,observed_at:purple.observed_at,confidence:purple.confidence}:null,latest_signal:sig?{key:sig.signal_key,label:sig.signal_label,value:sig.numeric_value,text:sig.text_value,unit:sig.unit,source_name:sig.source_name,source_url:sig.source_url,observed_at:sig.observed_at,confidence:sig.confidence}:null,mission_score:null,mission_score_status:'building'}})
  const schoolItems=(si.data||[]).map((x:any)=>{const vv=ver.get(`school:${x.id}`)||[];const explicitlyVerified=vv.some((z:any)=>z.verification_type==='official_source');const governmentBacked=x.source_type==='government_data'||officialSchoolSource(x.official_profile_url,x.source_url);return{...x,official_verified:explicitlyVerified||governmentBacked,community_verified:vv.some((z:any)=>z.verification_type==='community_user'),mission_score:x.mission_score||null,mission_score_status:x.mission_score?'rated':'building'}})
  const compact=(x:any)=>x?{key:x.signal_key,label:x.signal_label,value:x.numeric_value,text:x.text_value,unit:x.unit,source_name:x.source_name,source_url:x.source_url,source_type:x.source_type,observed_at:x.observed_at,confidence:x.confidence}:null
  const installations=(i.data||[]).map((x:any)=>{const a=ib.get(x.id)||[],latest=a[0],school=a.find((y:any)=>/school_liaison/i.test(String(y.signal_key))),pcs=a.find((y:any)=>/pcs|relocation/i.test(String(y.signal_key)+' '+String(y.signal_label))),preferred=school||pcs||latest;return{...x,signal_count:a.length,source_url:preferred?.source_url||null,official_verified:hasHttps(preferred?.source_url)&&(preferred?.source_type==='official'||/\.mil\b|\.gov\b/i.test(String(preferred?.source_url))),community_verified:(ver.get(`installation:${x.id}`)||[]).some((z:any)=>z.verification_type==='community_user'),mission_score:null,mission_score_status:'building',latest_signal:compact(latest),school_liaison:compact(school),pcs_support:compact(pcs)}})
  const deals=sourceBackedDeals.map((x:any)=>({...x,military_value_weight:dealWeight(x),official_verified:officialBusinessSource(x.businesses?.website_url,x.source_url)||/\.gov\b|\.mil\b/i.test(String(x.source_url)),community_verified:(ver.get(`deal:${x.id}`)||[]).some((z:any)=>z.verification_type==='community_user'),description:[x.description,`Verified ${day(x.verified_at)}.`,x.ends_at?`Listed end date ${day(x.ends_at)}.`:null].filter(Boolean).join(' ')})).sort((a:any,b:any)=>b.military_value_weight-a.military_value_weight)
  let suppressedOwnershipClaims=0
  const businesses=(b.data||[]).map((x:any)=>{const hs=hasHttps(x.source_url),unsupported=!hs&&(x.veteran_owned||x.military_spouse_owned);if(unsupported)suppressedOwnershipClaims++;const ownDeals=dealBy.get(x.id)||[],bestDeal=[...ownDeals].sort((a:any,b:any)=>dealWeight(b)-dealWeight(a))[0]||null,score=scoreBy.get(x.id),rating=ratingBy.get(x.id),vv=ver.get(`business:${x.id}`)||[];return{...x,veteran_owned:hs?x.veteran_owned:false,military_spouse_owned:hs?x.military_spouse_owned:false,has_active_military_offer:ownDeals.length>0,military_value_weight:bestDeal?dealWeight(bestDeal):0,best_military_offer:bestDeal?{title:bestDeal.title,value:bestDeal.offer_value_text,source_url:bestDeal.source_url,verified_at:bestDeal.verified_at}:null,public_rating:rating?{rating:rating.rating,scale:rating.rating_scale,sample_size:rating.sample_size,source_name:rating.source_name,source_url:rating.source_url,observed_at:rating.observed_at,confidence:rating.confidence}:null,mission_score:score?.review_count>0?score.mission_score:null,mission_review_count:score?.review_count||0,mission_score_status:score?.review_count>0?'rated':'building',official_verified:officialBusinessSource(x.website_url,x.source_url)||vv.some((z:any)=>z.verification_type==='official_source'),community_verified:vv.some((z:any)=>z.verification_type==='community_user'),provenance_status:hs?'sourced':'source_pending',source_freshness:hs&&x.source_checked_at?`Source checked ${day(x.source_checked_at)}`:null}}).sort((a:any,b:any)=>(b.military_value_weight-a.military_value_weight)||((b.public_rating?.sample_size||0)-(a.public_rating?.sample_size||0)))
  const sourced=businesses.filter((x:any)=>x.provenance_status==='sourced').length
  const payload=JSON.stringify({businesses,deals,schools:districts,school_items:schoolItems,installations,meta:{generated_at:new Date().toISOString(),cache_ttl_seconds:300,optional_sources_degraded:optionalErrors,individual_schools:schoolItems.length,school_signals:(ss.data||[]).length,installation_signals:(isig.data||[]).length,purple_star_districts:districts.filter((x:any)=>x.purple_star).length,sourced_businesses:sourced,source_pending_businesses:businesses.length-sourced,suppressed_deals_without_https_source:rawDeals.length-sourceBackedDeals.length,suppressed_ownership_claims_without_https_source:suppressedOwnershipClaims}})
  memoryCache=payload;memoryCacheAt=Date.now();return ok(payload)
 }catch(e){console.error('public-explore',e);if(memoryCache)return ok(memoryCache);return new Response(JSON.stringify({businesses:[],deals:[],schools:[],school_items:[],installations:[],meta:{degraded:true}}),{status:503,headers})}
})