const endpoints={explore:'https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/public-explore',auto:'https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/public-auto-dealers',support:'https://vquwdypidgjmxnhhdbol.supabase.co/functions/v1/public-support'};
const errors=[];const warnings=[];
const https=u=>typeof u==='string'&&/^https:\/\//i.test(u);
async function get(name,url){const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`${name} ${r.status}`);return r.json()}
const [explore,auto,support]=await Promise.all(Object.entries(endpoints).map(([n,u])=>get(n,u)));
for(const d of explore.deals||[]){if(!https(d.source_url))errors.push(`deal missing HTTPS source: ${d.title||d.id}`);if(d.official_verified&&!https(d.source_url))errors.push(`official deal verification without source: ${d.title||d.id}`)}
for(const b of explore.businesses||[]){if(b.mission_score_status==='rated'&&!(Number(b.mission_review_count)>0))errors.push(`rated business lacks MR reviews: ${b.name}`);if(b.public_rating&&(!https(b.public_rating.source_url)||!(Number(b.public_rating.sample_size)>=1)))warnings.push(`public rating missing source/sample: ${b.name}`);if(b.official_verified&&!https(b.source_url)&&!https(b.best_military_offer?.source_url))warnings.push(`official business verification has no public source in feed: ${b.name}`)}
for(const s of explore.school_items||[]){if(s.mission_score_status==='rated'&&s.mission_score==null)errors.push(`rated school missing score: ${s.name}`);if(s.mission_score_status!=='rated'&&s.mission_score!=null)errors.push(`building school exposes score: ${s.name}`);if(s.official_verified&&!https(s.official_profile_url)&&!https(s.source_url))errors.push(`official school lacks authoritative URL: ${s.name}`);if(s.purple_star_status&&!https(s.purple_star_source_url))warnings.push(`Purple Star status lacks source URL: ${s.name}`)}
for(const i of explore.installations||[]){if(i.mission_score_status==='rated'&&i.mission_score==null)errors.push(`rated installation missing score: ${i.name}`);if(i.mission_score_status!=='rated'&&i.mission_score!=null)errors.push(`building installation exposes score: ${i.name}`);if(i.official_verified&&!https(i.source_url))warnings.push(`official installation has no preferred source URL: ${i.name}`)}
for(const d of auto.dealers||[]){if(d.mr_status==='rated'&&d.mr_score==null)warnings.push(`rated dealer has no exposed MR score: ${d.name}`);if(d.public_rating!=null&&(!https(d.public_rating_url)||!(Number(d.public_review_count)>=1)))errors.push(`dealer public rating missing source/sample: ${d.name}`);if(d.official_military_evidence&&!https(d.evidence_url))errors.push(`dealer official military evidence lacks HTTPS source: ${d.name}`)}
for(const p of auto.salespeople||[]){if(p.mr_status==='rated'&&!p.user_verified&&!p.official_verified)errors.push(`rated salesperson lacks verification: ${p.name}`);if((p.mention_count||0)>0&&!https(p.source_url))errors.push(`salesperson evidence lacks source: ${p.name}`)}
const supportRows=Array.isArray(support)?support:(support.resources||support.items||[]);for(const r of supportRows){if(r.active!==false&&!https(r.source_url))errors.push(`active support resource lacks HTTPS source: ${r.name||r.slug||'unknown'}`)}
const summary={generated_at:new Date().toISOString(),counts:{businesses:(explore.businesses||[]).length,deals:(explore.deals||[]).length,school_items:(explore.school_items||[]).length,installations:(explore.installations||[]).length,dealers:(auto.dealers||[]).length,salespeople:(auto.salespeople||[]).length,support:supportRows.length},meta:explore.meta||{},warnings:[...new Set(warnings)].sort(),errors:[...new Set(errors)].sort()};
console.log(JSON.stringify(summary,null,2));if(errors.length)process.exit(1);
