import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, normalize } from 'node:path';
const root='.';const dist='dist';const errors=[];
const htmlNames=['index.html','military-value.html','schools.html','bases.html','neighborhoods.html','community.html','buy-a-car.html','support.html','business.html','events.html','auto.html'];
const releaseFiles=[...htmlNames,'sitemap.xml','robots.txt','feedback.js','rankings.js','quick-vote.js','reviews.js','community.js','lifestyle-nav.js','support-ui.js','auto-dealers.js','auto-detail.js','auto-detail-links.js','provenance.js','car-embed.js','support-embed.js','value-priority.js','live-trust-controls.js','discovery-sort.js','detail-links.js','evidence-freshness.js','evidence-coverage.js','lifestyle-home.js','mobile-browse.js'];
const read=path=>existsSync(path)?readFileSync(path,'utf8'):'';const requireFile=(path,label=path)=>{if(!existsSync(path))errors.push(`missing ${label}`)};const requireTokens=(text,tokens,label)=>{for(const token of tokens)if(!text.includes(token))errors.push(`${label} missing ${token}`)};const stripTarget=target=>String(target||'').split('#',1)[0].split('?',1)[0];const isExternal=target=>/^(?:https?:|mailto:|tel:|data:|javascript:|\/\/)/i.test(target);const candidatesForLocal=(htmlName,target)=>{const clean=stripTarget(target);if(!clean||clean.startsWith('#')||isExternal(clean)||clean.includes('${'))return[];const relative=clean.startsWith('/')?clean.slice(1):normalize(join(dirname(htmlName),clean));if(!relative)return['index.html'];if(relative.endsWith('/'))return[join(relative,'index.html')];if(/\.[A-Za-z0-9]+$/.test(relative))return[relative];return[relative,`${relative}.html`,join(relative,'index.html')]};
for(const name of releaseFiles){requireFile(name,`source release file: ${name}`);requireFile(`${dist}/${name}`,`built release file: dist/${name}`)}
try{JSON.parse(read('vercel.json'))}catch(error){errors.push(`invalid vercel.json: ${error.message}`)}
const feedback=read('feedback.js'),rankings=read('rankings.js'),quick=read('quick-vote.js'),reviews=read('reviews.js'),lifestyle=read('lifestyle-nav.js'),lifestyleHome=read('lifestyle-home.js'),supportUi=read('support-ui.js'),auto=read('auto-dealers.js'),autoDetail=read('auto-detail.js'),autoLinks=read('auto-detail-links.js'),trust=read('live-trust-controls.js'),discovery=read('discovery-sort.js'),freshness=read('evidence-freshness.js'),coverage=read('evidence-coverage.js'),mobile=read('mobile-browse.js');
requireTokens(feedback,['submit-beta-feedback'],'feedback');requireTokens(rankings,['MR OPEN'],'rankings');requireTokens(quick,['quick-rank-vote','▲','▼'],'quick sentiment controls');requireTokens(reviews,['submit-item-review','Pending / Unverified'],'reviews');requireTokens(lifestyle,['LIVE','SUPPORT','SAVE','/support','/buy-a-car','/community'],'lifestyle navigation');requireTokens(lifestyleHome,['Live better.','Support','Buy a Car','Events','Neighborhoods'],'lifestyle home');requireTokens(supportUi,['MR Building','Official Source Verified','supportQ'],'support hub');requireTokens(auto,['Official Source Verified','Official Website','User Verified','Unsourced public ratings are suppressed','Military evidence first','Freshest evidence','public-auto-dealers','External ratings never become Mission Rated scores.','Rating observed','Evidence observed','Building'],'auto dealer trust UX');requireTokens(autoDetail,['public-auto-dealers','MR ${','Official Source Verified','User Verified','Public rating source','Mission Rated does not convert third-party mentions into an MR score.'],'auto detail trust UX');requireTokens(autoLinks,['View sourced details','/auto?type=','public-auto-dealers'],'auto detail links');requireTokens(trust,['Official source','Military value','Public rating','Fresh evidence','Newest source','Live better. Get support. Save more.','public-explore','mrEvidenceDate'],'live trust controls');if(!trust.replaceAll(' ','').includes('age<=30'))errors.push('fresh evidence filter must enforce 30-day window');if(trust.includes("className='mrFreshness'")||trust.includes('className="mrFreshness"'))errors.push('trust script must not shadow evidence-freshness badge class');requireTokens(discovery,['Strongest military value','Highest sourced public rating','Most public reviews','Official-source evidence first','Strongest verified value','Most recently verified','MR Building','Public rating sourced','public-explore'],'discovery sorting');requireTokens(freshness,['Evidence fresh','Evidence ${d}d old','Freshness reflects the newest stored source observation','public-explore'],'evidence freshness UX');requireTokens(coverage,['public-explore'],'evidence coverage UX');requireTokens(mobile,['Clear filters','content-visibility:auto','safe-area-inset-bottom','Filters update results instantly'],'mobile browse UX');
for(const name of htmlNames){const built=read(`${dist}/${name}`);requireTokens(built,['/feedback.js','/lifestyle-nav.js','/mobile-browse.js'],`dist/${name}`)}
requireTokens(read(`${dist}/index.html`),['/live-trust-controls.js','/value-priority.js','/discovery-sort.js','/evidence-freshness.js','/evidence-coverage.js','/lifestyle-home.js'],'dist/index.html');requireTokens(read(`${dist}/support.html`),['/support-ui.js','/support-embed.js'],'dist/support.html');requireTokens(read(`${dist}/buy-a-car.html`),['/auto-dealers.js','/auto-detail-links.js','/car-embed.js'],'dist/buy-a-car.html');requireTokens(read(`${dist}/auto.html`),['/auto-detail.js'],'dist/auto.html');for(const name of ['index.html','military-value.html','schools.html','bases.html'])requireTokens(read(`${dist}/${name}`),['/evidence-freshness.js','/detail-links.js'],`dist/${name}`);for(const name of ['index.html','military-value.html','schools.html','bases.html','neighborhoods.html'])requireTokens(read(`${dist}/${name}`),['/reviews.js'],`dist/${name}`);
for(const name of readdirSync(root).filter(name=>name.endsWith('.html')).sort()){const text=read(name),low=text.toLowerCase();if(!low.includes('<html')||!low.includes('lang="en"'))errors.push(`${name}: missing lang`);if(!low.includes('name="viewport"'))errors.push(`${name}: missing viewport`);if(low.includes('http://'))errors.push(`${name}: insecure URL`);const tags=text.match(/<a\b[^>]*target=["']_blank["'][^>]*>/gi)||[];for(const tag of tags){const lower=tag.toLowerCase();if(!/rel=["'][^"']*noopener[^"']*["']/.test(lower))errors.push(`${name}: target blank missing noopener`)}for(const match of text.matchAll(/\b(?:href|src)=["']([^"']+)["']/gi)){const target=match[1],candidates=candidatesForLocal(name,target);if(candidates.length&&!candidates.some(candidate=>existsSync(candidate)))errors.push(`${name}: broken local target ${target}`)}}
const sitemap=read('sitemap.xml');for(const route of ['/military-value','/schools','/bases','/neighborhoods','/community','/buy-a-car','/support','/events'])if(!sitemap.includes(route))errors.push(`sitemap missing ${route}`);
if(errors.length){console.error('Mission Rated QA failed:');for(const error of [...new Set(errors)].sort())console.error(` - ${error}`);process.exit(1)}console.log('Mission Rated QA passed: build artifact, internal link integrity, trust states, sourced dealer and salesperson detail discovery, support, reviews, evidence freshness, lifestyle/events routing, mobile browse UX, and release files.');
