create table if not exists public.weekend_brief_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  email_normalized text generated always as (lower(trim(email))) stored,
  source text not null default 'missionratedhq.com',
  installation text,
  status text not null default 'active' check (status in ('active','unsubscribed')),
  consented_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint weekend_brief_email_format check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create unique index if not exists weekend_brief_subscribers_email_normalized_uidx
  on public.weekend_brief_subscribers (email_normalized);

alter table public.weekend_brief_subscribers enable row level security;
revoke all on table public.weekend_brief_subscribers from anon, authenticated;
grant select, insert, update, delete on table public.weekend_brief_subscribers to service_role;

comment on table public.weekend_brief_subscribers is 'Opt-in subscribers for the Mission Rated Weekend Brief. Not exposed directly to anonymous clients.';
